(()=>{
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>window.user?.id||(typeof user!=='undefined'?user?.id:null);
const media=(bucket,path)=>path?sb.storage.from(bucket).getPublicUrl(path).data.publicUrl:'';
const DAILY=[
 ['30 jongles pied faible','Réalise 30 jongles uniquement avec ton pied faible.','🦶'],
 ['Lucarne challenge','Place une frappe dans une lucarne.','🎯'],
 ['Contrôle orienté + frappe','Enchaîne un contrôle orienté puis une frappe cadrée.','💥'],
 ['10 jongles tête','Réalise 10 jongles de la tête sans laisser tomber le ballon.','🧠'],
 ['Crossbar','Touche la barre transversale en une frappe.','🥅'],
 ['Slalom 6 plots','Effectue un slalom rapide entre 6 plots avec le ballon.','🚀'],
 ['Tour du monde','Réalise un tour du monde propre en vidéo.','🌍']
];
function dayKey(){const d=new Date();return d.toISOString().slice(0,10)}
function challenge(){const n=Math.floor(new Date(dayKey()+'T00:00:00Z').getTime()/86400000);return DAILY[Math.abs(n)%DAILY.length]}
function inject(){
 if($('feedDrawer'))return;
 const home=$('globalRanking')?.closest('.global-rank-card')||document.querySelector('.leftcol .panel');
 if(home){
   const wrap=document.createElement('div');wrap.innerHTML=`<div class="panel" style="margin-top:12px;background:linear-gradient(145deg,#12291c,#07110c);border:1px solid #315c42"><div style="display:flex;gap:10px;align-items:center"><div style="font-size:34px">🔥</div><div style="flex:1"><b>Défi du jour</b><div id="dailyMini" class="msg">Chargement…</div></div><button id="dailyOpen" class="primary">Participer</button></div></div><div class="panel" style="margin-top:12px"><div style="display:flex;gap:10px;align-items:center"><div style="font-size:32px">📹</div><div style="flex:1"><b>FootShow Feed</b><div class="msg">Les meilleures actions en plein écran.</div></div><button id="feedOpen" class="primary">Regarder</button></div></div><div class="panel" style="margin-top:12px"><div style="display:flex;gap:10px;align-items:center"><div style="font-size:32px">📊</div><div style="flex:1"><b>Mes statistiques</b><div id="statsMini" class="msg">Classement, vues et progression.</div></div><button id="statsOpen" class="secondary">Voir</button></div></div>`;home.after(...wrap.children);
 }
 document.body.insertAdjacentHTML('beforeend',`<section id="feedDrawer" class="drawer hidden"><div class="drawer-inner" style="max-width:520px;padding:8px"><button id="feedClose" class="close">×</button><div id="feedContent"></div></div></section><section id="dailyDrawer" class="drawer hidden"><div class="drawer-inner" style="max-width:620px"><button id="dailyClose" class="close">×</button><div id="dailyContent"></div></div></section><section id="statsDrawer" class="drawer hidden"><div class="drawer-inner" style="max-width:680px"><button id="statsClose" class="close">×</button><div id="statsContent"></div></div></section>`);
 $('feedOpen')?.addEventListener('click',openFeed);$('feedClose')?.addEventListener('click',()=>$('feedDrawer').classList.add('hidden'));
 $('dailyOpen')?.addEventListener('click',openDaily);$('dailyClose')?.addEventListener('click',()=>$('dailyDrawer').classList.add('hidden'));
 $('statsOpen')?.addEventListener('click',openStats);$('statsClose')?.addEventListener('click',()=>$('statsDrawer').classList.add('hidden'));
 const c=challenge();if($('dailyMini'))$('dailyMini').textContent=`${c[2]} ${c[0]} · +40 pts`;
 setTimeout(loadStatsMini,1200);
}
async function openFeed(){
 $('feedDrawer').classList.remove('hidden');const root=$('feedContent');root.innerHTML='<div class="msg" style="padding:30px">Chargement du feed…</div>';
 const {data,error}=await sb.from('videos').select('id,user_id,storage_path,action_type,caption,created_at,profiles:user_id(full_name,username,avatar_url,position,category),likes(user_id),comments(id)').order('created_at',{ascending:false}).limit(40);
 if(error){root.innerHTML=`<div class="msg">${esc(error.message)}</div>`;return}
 root.innerHTML=`<style>.fs-feed{height:calc(100dvh - 90px);overflow-y:auto;scroll-snap-type:y mandatory;border-radius:22px}.fs-reel{height:calc(100dvh - 105px);min-height:560px;position:relative;scroll-snap-align:start;background:#000;border-radius:22px;overflow:hidden;margin-bottom:8px}.fs-reel video{width:100%;height:100%;object-fit:contain;background:#000}.reelShade{position:absolute;inset:auto 0 0;padding:90px 18px 24px;background:linear-gradient(transparent,#000d);pointer-events:none}.reelUser{font-weight:900;font-size:18px}.reelActions{position:absolute;right:12px;bottom:105px;display:grid;gap:11px}.reelBtn{width:54px;height:54px;border-radius:50%;border:1px solid #ffffff35;background:#07120dcc;color:#fff;font-size:20px;font-weight:900}.reelBtn small{display:block;font-size:9px}</style><div class="fs-feed">${(data||[]).map(v=>{const p=v.profiles||{},liked=(v.likes||[]).some(x=>x.user_id===uid());return `<article class="fs-reel" data-video="${v.id}"><video playsinline controls preload="metadata" src="${esc(media('footshow-videos',v.storage_path))}"></video><div class="reelShade"><div class="reelUser">${esc(p.full_name||p.username||'Joueur')}</div><div class="msg">${esc([p.position,p.category].filter(Boolean).join(' · '))}</div><b>${esc(v.action_type||'Action')}</b>${v.caption?`<div>${esc(v.caption)}</div>`:''}</div><div class="reelActions"><button class="reelBtn" data-like="${v.id}" data-liked="${liked?'1':'0'}">${liked?'❤️':'♡'}<small>${(v.likes||[]).length}</small></button><button class="reelBtn" data-profile="${v.user_id}">👤<small>Profil</small></button><button class="reelBtn" data-comment="${v.id}">💬<small>${(v.comments||[]).length}</small></button></div></article>`}).join('')||'<div class="msg">Aucune vidéo.</div>'}</div>`;
 root.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{ $('feedDrawer').classList.add('hidden');window.openPlayer?.(b.dataset.profile)});
 root.querySelectorAll('[data-comment]').forEach(b=>b.onclick=()=>window.commentOn?.(b.dataset.comment));
 root.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{const liked=b.dataset.liked==='1',id=b.dataset.like;const r=liked?await sb.from('likes').delete().eq('video_id',id).eq('user_id',uid()):await sb.from('likes').insert({video_id:id,user_id:uid()});if(!r.error){b.dataset.liked=liked?'0':'1';b.firstChild.nodeValue=liked?'♡':'❤️';window.loadGlobalRanking?.()}});
 const io=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target.querySelector('video');if(!v)return;if(e.isIntersecting&&e.intersectionRatio>.7){v.play().catch(()=>{});recordView(e.target.dataset.video)}else v.pause()}),{threshold:[.7]});root.querySelectorAll('.fs-reel').forEach(x=>io.observe(x));
}
const seen=new Set();async function recordView(videoId){if(!videoId||seen.has(videoId)||!uid())return;seen.add(videoId);try{await sb.from('video_views').upsert({video_id:videoId,user_id:uid(),view_day:dayKey()},{onConflict:'video_id,user_id,view_day'})}catch(e){}}
async function openDaily(){
 $('dailyDrawer').classList.remove('hidden');const c=challenge(),root=$('dailyContent');
 root.innerHTML=`<div style="font-size:11px;color:#4ade80;font-weight:900;letter-spacing:1px">DÉFI DU JOUR · ${dayKey()}</div><div style="font-size:60px;margin-top:8px">${c[2]}</div><h2 style="font-size:30px;margin:4px 0">${c[0]}</h2><p>${c[1]}</p><div style="padding:12px;border:1px solid #315c42;border-radius:16px;background:#0a1710;margin:15px 0"><b style="color:#4ade80">+40 points FootShow</b><div class="msg">Une participation validée par jour et par joueur.</div></div><label>Ta vidéo</label><input id="dailyFile" type="file" accept="video/*" class="input"><label>Légende (facultatif)</label><textarea id="dailyCaption" class="input" rows="2"></textarea><button id="dailySubmit" class="primary full">🔥 Envoyer ma participation</button><p id="dailyMsg" class="msg"></p><h3 style="margin-top:25px">Participants aujourd’hui</h3><div id="dailyEntries"><div class="msg">Chargement…</div></div>`;
 $('dailySubmit').onclick=submitDaily;loadDailyEntries();
}
async function submitDaily(){const f=$('dailyFile').files[0];if(!f)return $('dailyMsg').textContent='Choisis une vidéo.';if(f.size>200*1024*1024)return $('dailyMsg').textContent='200 Mo maximum.';$('dailyMsg').textContent='Envoi en cours…';try{const ext=f.name.split('.').pop()||'mp4',path=`${uid()}/daily/${dayKey()}-${Date.now()}.${ext}`;const up=await sb.storage.from('footshow-videos').upload(path,f,{contentType:f.type});if(up.error)throw up.error;const {error}=await sb.from('daily_challenge_entries').insert({user_id:uid(),challenge_day:dayKey(),challenge_key:challenge()[0],storage_path:path,caption:$('dailyCaption').value.trim()||null});if(error)throw error;$('dailyMsg').textContent='Participation enregistrée ✅ +40 pts';loadDailyEntries();window.loadGlobalRanking?.();}catch(e){$('dailyMsg').textContent=e.message.includes('duplicate')?'Tu as déjà participé au défi du jour.':e.message}}
async function loadDailyEntries(){const root=$('dailyEntries');if(!root)return;const {data,error}=await sb.from('daily_challenge_entries').select('id,user_id,storage_path,caption,profiles:user_id(full_name,username)').eq('challenge_day',dayKey()).order('created_at',{ascending:false});if(error){root.innerHTML='<div class="msg">Active la table du défi quotidien dans Supabase.</div>';return}root.innerHTML=(data||[]).map(x=>`<div style="display:flex;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid #ffffff12"><video src="${esc(media('footshow-videos',x.storage_path))}" controls playsinline preload="metadata" style="width:82px;height:110px;object-fit:cover;border-radius:10px;background:#000"></video><div><b>${esc(x.profiles?.full_name||x.profiles?.username||'Joueur')}</b><div class="msg">${esc(x.caption||challenge()[0])}</div></div></div>`).join('')||'<div class="msg">Sois le premier à participer aujourd’hui.</div>'}
async function loadStatsMini(){try{const {data}=await sb.rpc('get_player_stats',{p_user_id:uid()});const s=data?.[0];if(s&&$('statsMini'))$('statsMini').textContent=`#${s.global_rank||'—'} global · #${s.category_rank||'—'} ${s.category||''} · ${s.total_views||0} vues`;}catch(e){}}
async function openStats(){
 $('statsDrawer').classList.remove('hidden');const root=$('statsContent');root.innerHTML='<div class="msg">Calcul de tes statistiques…</div>';
 try{const {data,error}=await sb.rpc('get_player_stats',{p_user_id:uid()});if(error)throw error;const s=data?.[0]||{};root.innerHTML=`<div style="font-size:11px;color:#4ade80;font-weight:900;letter-spacing:1px">MON TABLEAU DE BORD</div><h2>📊 Mes statistiques FootShow</h2><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:10px"><div class="panel"><div class="msg">Points</div><b style="font-size:30px;color:#4ade80">${s.total_points||0}</b></div><div class="panel"><div class="msg">Classement global</div><b style="font-size:30px">#${s.global_rank||'—'}</b></div><div class="panel"><div class="msg">Classement ${esc(s.category||'catégorie')}</div><b style="font-size:30px">#${s.category_rank||'—'}</b></div><div class="panel"><div class="msg">Classement zone</div><b style="font-size:30px">#${s.zone_rank||'—'}</b></div><div class="panel"><div class="msg">Vues vidéos</div><b style="font-size:30px">${s.total_views||0}</b></div><div class="panel"><div class="msg">Likes reçus</div><b style="font-size:30px">${s.total_likes||0}</b></div></div><div class="panel" style="margin-top:12px"><b>🎬 ${s.video_count||0} vidéos publiées</b><div class="msg">🔥 ${s.daily_count||0} défis du jour réalisés · 🏆 ${s.contest_count||0} concours · 🧠 ${s.quiz_points||0} pts quiz · 🎮 ${s.game_points||0} pts jeu</div></div>`;}catch(e){root.innerHTML='<div class="msg">Les statistiques avancées seront disponibles après activation du script Supabase.</div>'}
}
document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,900));
})();