import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.55.0'
const sbx=createClient('https://nbhkvxfovrzhvdbdyxmy.supabase.co','sb_publishable_VTcWIZ2ibkOP8coT-GiPXw_XLqiacbZ')
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
let me=null
async function init(){const {data:{session}}=await sbx.auth.getSession();if(!session)return;me=session.user;const tabs=document.querySelector('.tabs');if(!tabs||document.getElementById('messagesTab'))return;tabs.insertAdjacentHTML('beforeend','<button class="tab" id="messagesTab" data-tab="extras">Messages & avis</button>');document.querySelector('.tabs').insertAdjacentHTML('afterend','<div id="extras" class="panel"></div>');document.getElementById('messagesTab').onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById('messagesTab').classList.add('active');document.getElementById('extras').classList.add('active');loadExtras()}}
async function loadExtras(){const {data:prof}=await sbx.from('profiles').select('*').eq('id',me.id).single();if(prof.role==='artisan')await artisanExtras(prof);else await clientExtras()}
async function artisanExtras(prof){const {data:ms=[]}=await sbx.from('matches').select('*').eq('artisan_id',me.id);const ids=ms.map(x=>x.project_id);let projects=[];if(ids.length){const r=await sbx.from('projects').select('*').in('id',ids);projects=r.data||[]}const {data:reviews=[]}=await sbx.from('reviews').select('*').eq('artisan_id',me.id);const avg=reviews.length?(reviews.reduce((a,r)=>a+r.rating,0)/reviews.length).toFixed(1):'—';document.getElementById('extras').innerHTML=`<div class="dashGrid"><div class="stat"><strong>${avg}</strong><span>note moyenne /5</span></div><div class="stat"><strong>${reviews.length}</strong><span>avis client(s)</span></div><div class="stat"><strong>${prof.verified?'✓':'En attente'}</strong><span>vérification artisan</span></div></div><div class="item" style="margin-top:16px"><h3>Vérification du profil</h3><p>Renseignez votre SIRET dans Mon profil. Le badge vérifié est attribué après contrôle des informations professionnelles.</p></div><h2>Messagerie</h2>${ms.map(m=>{const p=projects.find(x=>x.id===m.project_id)||{};return `<div class="item"><b>${E(p.title||'Projet')}</b><div id="chat-${m.project_id}"></div><form onsubmit="sendExtra(event,'${m.project_id}','${E(p.client_id)}')" class="actions"><input required name="body" placeholder="Votre message…" style="flex:1;padding:12px;border:1px solid #cbd5e1;border-radius:10px"><button class="btn primary">Envoyer</button></form></div>`}).join('')||'<div class="notice">Aucune conversation pour le moment.</div>'}`;for(const m of ms)loadChat(m.project_id)}
async function clientExtras(){const {data:ps=[]}=await sbx.from('projects').select('*').eq('client_id',me.id);const ids=ps.map(x=>x.id);let ms=[];if(ids.length){const r=await sbx.from('matches').select('*').in('project_id',ids);ms=r.data||[]}const aids=[...new Set(ms.map(x=>x.artisan_id))];let arts=[];if(aids.length){const r=await sbx.from('profiles').select('id,company_name,full_name').in('id',aids);arts=r.data||[]}document.getElementById('extras').innerHTML=`<h2>Messages avec vos artisans</h2>${ms.map(m=>{const p=ps.find(x=>x.id===m.project_id)||{},a=arts.find(x=>x.id===m.artisan_id)||{};return `<div class="item"><h3>${E(a.company_name||a.full_name||'Artisan')} — ${E(p.title)}</h3><div id="chat-${m.project_id}-${m.artisan_id}"></div><form onsubmit="sendExtra(event,'${m.project_id}','${m.artisan_id}')" class="actions"><input required name="body" placeholder="Votre message…" style="flex:1;padding:12px;border:1px solid #cbd5e1;border-radius:10px"><button class="btn primary">Envoyer</button></form><form onsubmit="reviewExtra(event,'${m.project_id}','${m.artisan_id}')" class="actions"><select name="rating"><option value="5">★★★★★ 5/5</option><option value="4">★★★★ 4/5</option><option value="3">★★★ 3/5</option><option value="2">★★ 2/5</option><option value="1">★ 1/5</option></select><input name="comment" placeholder="Votre avis"><button class="btn ghost">Publier l’avis</button></form></div>`}).join('')||'<div class="notice">Vos conversations apparaîtront ici après un matching.</div>'}`;for(const m of ms)loadChat(m.project_id,m.artisan_id)}
async function loadChat(project,artisan){let q=sbx.from('messages').select('*').eq('project_id',project).order('created_at');const {data=[]}=await q;const el=document.getElementById(artisan?`chat-${project}-${artisan}`:`chat-${project}`);if(el)el.innerHTML=data.map(x=>`<div class="notice ${x.sender_id===me.id?'success':''}" style="margin:8px 0"><b>${x.sender_id===me.id?'Vous':'Interlocuteur'} :</b> ${E(x.body)}</div>`).join('')}
window.sendExtra=async(e,project,recipient)=>{e.preventDefault();const body=e.target.body.value.trim();const {error}=await sbx.from('messages').insert({project_id:project,sender_id:me.id,recipient_id:recipient,body});if(error)return alert(error.message);e.target.reset();loadExtras()}
window.reviewExtra=async(e,project,artisan)=>{e.preventDefault();const {error}=await sbx.from('reviews').insert({project_id:project,client_id:me.id,artisan_id:artisan,rating:Number(e.target.rating.value),comment:e.target.comment.value.trim()});if(error)return alert(error.message);alert('Merci, votre avis a été publié.');loadExtras()}
sbx.auth.onAuthStateChange((_,s)=>{if(s){me=s.user;setTimeout(init,200)}});init();