import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.55.0'
const sbx=createClient('https://nbhkvxfovrzhvdbdyxmy.supabase.co','sb_publishable_VTcWIZ2ibkOP8coT-GiPXw_XLqiacbZ')
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));let me=null
async function init(){const {data:{session}}=await sbx.auth.getSession();if(!session)return;me=session.user;const tabs=document.querySelector('.tabs');if(!tabs||document.getElementById('messagesTab'))return;tabs.insertAdjacentHTML('beforeend','<button class="tab" id="messagesTab">Messages, photos & avis</button>');tabs.insertAdjacentHTML('afterend','<div id="extras" class="panel"></div>');document.getElementById('messagesTab').onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));messagesTab.classList.add('active');extras.classList.add('active');loadExtras()}}
async function loadExtras(){const {data:p}=await sbx.from('profiles').select('*').eq('id',me.id).single();p.role==='artisan'?artisanExtras(p):clientExtras()}
const photoForm=p=>`<form onsubmit="uploadPhoto(event,'${p}')" class="actions"><input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required><button class="btn ghost">Ajouter une photo</button></form><div id="photos-${p}" class="actions"></div>`
async function artisanExtras(prof){const {data:ms=[]}=await sbx.from('matches').select('*').eq('artisan_id',me.id);const ids=ms.map(x=>x.project_id);let ps=[];if(ids.length){const r=await sbx.from('projects').select('*').in('id',ids);ps=r.data||[]}const {data:rv=[]}=await sbx.from('reviews').select('*').eq('artisan_id',me.id);const avg=rv.length?(rv.reduce((a,r)=>a+r.rating,0)/rv.length).toFixed(1):'—';extras.innerHTML=`<div class="dashGrid"><div class="stat"><strong>${avg}</strong><span>note /5</span></div><div class="stat"><strong>${rv.length}</strong><span>avis</span></div><div class="stat"><strong>${prof.verified?'✓':'En attente'}</strong><span>profil vérifié</span></div></div><div class="item"><h3>Vérification artisan</h3><p>Complétez votre SIRET dans Mon profil. ArtisanMatch pourra ensuite contrôler vos informations et attribuer le badge vérifié.</p></div><h2>Vos échanges</h2>${ms.map(m=>{const p=ps.find(x=>x.id===m.project_id)||{};return `<div class="item"><h3>${E(p.title||'Projet')}</h3><div id="chat-${m.project_id}"></div><form onsubmit="sendExtra(event,'${m.project_id}','${p.client_id}')" class="actions"><input required name="body" placeholder="Votre message…"><button class="btn primary">Envoyer</button></form>${photoForm(m.project_id)}</div>`}).join('')||'<div class="notice">Aucune conversation.</div>'}`;for(const m of ms){loadChat(m.project_id);loadPhotos(m.project_id)}}
async function clientExtras(){const {data:ps=[]}=await sbx.from('projects').select('*').eq('client_id',me.id);const ids=ps.map(x=>x.id);let ms=[];if(ids.length){const r=await sbx.from('matches').select('*').in('project_id',ids);ms=r.data||[]}const aids=[...new Set(ms.map(x=>x.artisan_id))];let arts=[];if(aids.length){const r=await sbx.from('profiles').select('id,company_name,full_name,verified').in('id',aids);arts=r.data||[]}extras.innerHTML=`<h2>Messages, photos & avis</h2>${ms.map(m=>{const p=ps.find(x=>x.id===m.project_id)||{},a=arts.find(x=>x.id===m.artisan_id)||{};return `<div class="item"><h3>${E(a.company_name||a.full_name||'Artisan')} ${a.verified?'✓':''} — ${E(p.title)}</h3><div id="chat-${m.project_id}-${m.artisan_id}"></div><form onsubmit="sendExtra(event,'${m.project_id}','${m.artisan_id}')" class="actions"><input required name="body" placeholder="Votre message…"><button class="btn primary">Envoyer</button></form>${photoForm(m.project_id)}<form onsubmit="reviewExtra(event,'${m.project_id}','${m.artisan_id}')" class="actions"><select name="rating"><option value="5">★★★★★ 5/5</option><option value="4">★★★★ 4/5</option><option value="3">★★★ 3/5</option><option value="2">★★ 2/5</option><option value="1">★ 1/5</option></select><input name="comment" placeholder="Votre avis"><button class="btn ghost">Publier l’avis</button></form></div>`}).join('')||'<div class="notice">Vos échanges apparaîtront après un matching.</div>'}`;for(const m of ms){loadChat(m.project_id,m.artisan_id);loadPhotos(m.project_id)}}
async function loadChat(project,artisan){const {data=[]}=await sbx.from('messages').select('*').eq('project_id',project).order('created_at');const el=document.getElementById(artisan?`chat-${project}-${artisan}`:`chat-${project}`);if(el)el.innerHTML=data.filter(x=>!artisan||x.sender_id===artisan||x.recipient_id===artisan).map(x=>`<div class="notice ${x.sender_id===me.id?'success':''}"><b>${x.sender_id===me.id?'Vous':'Interlocuteur'} :</b> ${E(x.body)}</div>`).join('')}
async function loadPhotos(project){const {data=[]}=await sbx.from('project_photos').select('*').eq('project_id',project).order('created_at');const el=document.getElementById(`photos-${project}`);if(el)el.innerHTML=data.map(x=>`<a href="${E(x.photo_url)}" target="_blank"><img src="${E(x.photo_url)}" alt="Photo chantier" style="width:90px;height:70px;object-fit:cover;border-radius:10px"></a>`).join('')}
window.sendExtra=async(e,p,r)=>{e.preventDefault();const {error}=await sbx.from('messages').insert({project_id:p,sender_id:me.id,recipient_id:r,body:e.target.body.value.trim()});if(error)return alert(error.message);e.target.reset();loadExtras()}
window.uploadPhoto=async(e,p)=>{e.preventDefault();const f=e.target.photo.files[0];if(!f)return;const path=`${me.id}/${p}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await sbx.storage.from('project-photos').upload(path,f);if(error)return alert(error.message);const {data:u}=sbx.storage.from('project-photos').getPublicUrl(path);const r=await sbx.from('project_photos').insert({project_id:p,owner_id:me.id,photo_url:u.publicUrl});if(r.error)return alert(r.error.message);e.target.reset();loadPhotos(p)}
window.reviewExtra=async(e,p,a)=>{e.preventDefault();const {error}=await sbx.from('reviews').insert({project_id:p,client_id:me.id,artisan_id:a,rating:Number(e.target.rating.value),comment:e.target.comment.value.trim()});if(error)return alert(error.message);alert('Merci, votre avis a été publié.');loadExtras()}
sbx.auth.onAuthStateChange((_,s)=>{if(s){me=s.user;setTimeout(init,200)}});init();