(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const uid=()=>window.user?.id||(typeof user!=='undefined'?user?.id:null);
const media=(bucket,path)=>path?sb.storage.from(bucket).getPublicUrl(path).data.publicUrl:'';
function ensure(){let d=document.getElementById('tiktokFeedDrawer');if(d)return d;d=document.createElement('section');d.id='tiktokFeedDrawer';d.className='drawer hidden';d.innerHTML='<div class="drawer-inner tiktok-shell"><button id="closeTikTokFeed" class="close tiktok-close">×</button><div class="tiktok-title">FootShow Feed</div><div id="tiktokFeed"></div></div>';document.body.appendChild(d);document.getElementById('closeTikTokFeed').onclick=()=>{d.classList.add('hidden');pauseAll()};return d}
function pauseAll(){document.querySelectorAll('#tiktokFeed video').forEach(v=>v.pause())}
async function openFeed(){const d=ensure(),root=document.getElementById('tiktokFeed');d.classList.remove('hidden');root.innerHTML='<div class="msg" style="padding:30px">Chargement du feed…</div>';
 const {data,error}=await sb.from('videos').select('id,user_id,storage_path,action_type,caption,opponent,competition,created_at,profiles:user_id(full_name,username,avatar_url,position,category,club),likes(user_id),comments(id,user_id,body,created_at)').order('created_at',{ascending:false}).limit(60);
 if(error){root.innerHTML=`<div class="msg" style="padding:30px">${esc(error.message)}</div>`;return}
 root.innerHTML=`<style>
 #tiktokFeedDrawer{background:#000!important}.tiktok-shell{max-width:520px!important;width:100%!important;height:100dvh!important;padding:0!important;background:#000!important;overflow:hidden!important;position:relative}.tiktok-title{position:absolute;top:max(14px,env(safe-area-inset-top));left:18px;z-index:20;color:#fff;font-weight:900;font-size:18px;text-shadow:0 2px 12px #000}.tiktok-close{position:absolute!important;top:max(10px,env(safe-area-inset-top))!important;right:12px!important;z-index:30!important;background:#0008!important;color:#fff!important}.tt-wrap{height:100dvh;overflow-y:auto;scroll-snap-type:y mandatory;overscroll-behavior-y:contain;background:#000}.tt-card{height:100dvh;scroll-snap-align:start;position:relative;background:#000;overflow:hidden}.tt-card video{width:100%;height:100%;object-fit:contain;background:#000;display:block}.tt-grad{position:absolute;inset:auto 0 0 0;height:45%;background:linear-gradient(transparent,#000c 58%,#000);pointer-events:none}.tt-meta{position:absolute;left:16px;right:88px;bottom:28px;color:#fff;z-index:5;text-shadow:0 2px 10px #000}.tt-user{display:flex;align-items:center;gap:10px;margin-bottom:8px}.tt-avatar{width:42px;height:42px;border-radius:50%;object-fit:cover;border:2px solid #fff;background:#203329}.tt-name{font-size:17px;font-weight:900}.tt-sub{font-size:12px;color:#d5ddd8}.tt-caption{font-size:14px;line-height:1.35;margin-top:7px}.tt-actions{position:absolute;right:12px;bottom:34px;z-index:7;display:flex;flex-direction:column;align-items:center;gap:15px}.tt-action{border:0;background:#0008;color:#fff;width:54px;height:54px;border-radius:50%;font-size:22px;display:grid;place-items:center;backdrop-filter:blur(6px);box-shadow:0 3px 14px #0006}.tt-count{font-size:11px;color:#fff;margin-top:-10px;text-shadow:0 1px 7px #000}.tt-play{position:absolute;inset:0;display:grid;place-items:center;pointer-events:none;z-index:3}.tt-play span{display:none;width:78px;height:78px;border-radius:50%;background:#0008;color:#fff;font-size:36px;place-items:center}.tt-card.paused .tt-play span{display:grid}.tt-empty{padding:40px;color:#cbd5ce;text-align:center}
 @media(min-width:700px){.tiktok-shell{height:min(900px,96vh)!important;border-radius:24px}.tt-wrap,.tt-card{height:min(900px,96vh)}}
 </style><div class="tt-wrap">${(data||[]).map(v=>{const p=v.profiles||{},liked=(v.likes||[]).some(x=>x.user_id===uid()),src=media('footshow-videos',v.storage_path),av=media('avatars',p.avatar_url);return `<article class="tt-card paused" data-video-id="${v.id}" data-user-id="${v.user_id}"><video muted playsinline loop preload="metadata" src="${esc(src)}"></video><div class="tt-play"><span>▶</span></div><div class="tt-grad"></div><div class="tt-meta"><div class="tt-user"><img class="tt-avatar" src="${esc(av)}" onerror="this.style.visibility='hidden'"><div><div class="tt-name">${esc(p.full_name||p.username||'Joueur')}</div><div class="tt-sub">${esc([p.position,p.category,p.club].filter(Boolean).join(' · '))}</div></div></div><div class="tt-caption">${esc(v.caption||[v.action_type,v.opponent&&'vs '+v.opponent,v.competition].filter(Boolean).join(' · ')||'Action FootShow')}</div></div><div class="tt-actions"><button class="tt-action" data-like="${v.id}" data-liked="${liked?'1':'0'}">${liked?'❤️':'🤍'}</button><div class="tt-count" data-like-count="${v.id}">${(v.likes||[]).length}</div><button class="tt-action" data-comment="${v.id}">💬</button><div class="tt-count" data-comment-count="${v.id}">${(v.comments||[]).length}</div><button class="tt-action" data-profile="${v.user_id}">👤</button><div class="tt-count">Profil</div></div></article>`}).join('')||'<div class="tt-empty">Aucune vidéo publiée.</div>'}</div>`;
 bind(root);activateObserver(root)
}
function bind(root){root.querySelectorAll('.tt-card').forEach(card=>{const v=card.querySelector('video');card.addEventListener('click',e=>{if(e.target.closest('button'))return;if(v.paused){v.play().catch(()=>{});card.classList.remove('paused')}else{v.pause();card.classList.add('paused')}})});
 root.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{document.getElementById('tiktokFeedDrawer').classList.add('hidden');pauseAll();window.openPlayer?.(b.dataset.profile)});
 root.querySelectorAll('[data-comment]').forEach(b=>b.onclick=async()=>{const id=b.dataset.comment,body=prompt('Écrire un commentaire');if(!body?.trim())return;const me=uid();if(!me){alert('Connecte-toi pour commenter.');return}b.disabled=true;const {error}=await sb.from('comments').insert({video_id:id,user_id:me,body:body.trim()});b.disabled=false;if(error){alert('Commentaire non enregistré : '+error.message);return}const c=root.querySelector(`[data-comment-count="${id}"]`);if(c)c.textContent=String(Number(c.textContent||0)+1);if(window.toast)window.toast('Commentaire publié ✅')});
 root.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{const id=b.dataset.like,liked=b.dataset.liked==='1';const r=liked?await sb.from('likes').delete().eq('video_id',id).eq('user_id',uid()):await sb.from('likes').insert({video_id:id,user_id:uid()});if(r.error)return;const c=root.querySelector(`[data-like-count="${id}"]`);let n=Number(c?.textContent||0)+(liked?-1:1);if(c)c.textContent=Math.max(0,n);b.dataset.liked=liked?'0':'1';b.textContent=liked?'🤍':'❤️';window.loadGlobalRanking?.()})}
function activateObserver(root){const cards=[...root.querySelectorAll('.tt-card')];if(!cards.length)return;const io=new IntersectionObserver(entries=>{entries.forEach(en=>{const card=en.target,v=card.querySelector('video');if(en.isIntersecting&&en.intersectionRatio>.65){document.querySelectorAll('#tiktokFeed video').forEach(x=>{if(x!==v)x.pause()});v.play().then(()=>card.classList.remove('paused')).catch(()=>card.classList.add('paused'))}else{v.pause();card.classList.add('paused')}})},{root:root.querySelector('.tt-wrap'),threshold:[.25,.65,.9]});cards.forEach(c=>io.observe(c))}
window.openFootShowFeedV2=openFeed;window.openFootShowTikTokFeed=openFeed;
document.addEventListener('click',e=>{if(e.target.closest('#openFeedV2')){e.preventDefault();e.stopPropagation();openFeed()}},true);
})();