const SUPABASE_URL='https://nkbgrblydbyvanazwwsi.supabase.co';
const SUPABASE_KEY='sb_publishable_mcCTXBKCbPIjkFbv-o0qRg_PihOsR3-';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const positions=['Gardien de but','Latéral droit','Défenseur central','Latéral gauche','Piston droit','Piston gauche','Milieu défensif','Milieu central','Milieu relayeur','Milieu offensif','Ailier droit','Ailier gauche','Second attaquant','Avant-centre'];
const categories=['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19','U20','U21','Sénior','Vétéran'];
let user=null,me=null,selectedPlayer=null;
function fillSelects(){document.querySelectorAll('.position-select').forEach((s,i)=>{s.innerHTML=`<option value="">${i===1?'Tous les postes':'Choisir un poste'}</option>`+positions.map(x=>`<option>${x}</option>`).join('')});document.querySelectorAll('.category-select').forEach((s,i)=>{s.innerHTML=`<option value="">${i===1?'Toutes les catégories':'Choisir une catégorie'}</option>`+categories.map(x=>`<option>${x}</option>`).join('')})}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function media(bucket,path){return path?sb.storage.from(bucket).getPublicUrl(path).data.publicUrl:''}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('bottomNav').classList.add('hidden')}
async function boot(){fillSelects();const {data:{session}}=await sb.auth.getSession();if(!session)return showAuth();user=session.user;await enterApp()}
async function enterApp(){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('bottomNav').classList.remove('hidden');await loadMe();await loadPlayers();}
async function loadMe(){const {data}=await sb.from('profiles').select('*').eq('id',user.id).single();me=data}
$('loginTab').onclick=()=>{$('loginForm').classList.remove('hidden');$('signupForm').classList.add('hidden');$('loginTab').classList.add('active');$('signupTab').classList.remove('active')};
$('signupTab').onclick=()=>{$('signupForm').classList.remove('hidden');$('loginForm').classList.add('hidden');$('signupTab').classList.add('active');$('loginTab').classList.remove('active')};
$('signupType').onchange=()=>{$('playerSignupFields').classList.toggle('hidden',$('signupType').value!=='player')};
$('loginBtn').onclick=async()=>{const {data,error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});$('authMsg').textContent=error?error.message:'';if(!error){user=data.user;await enterApp()}};
$('signupBtn').onclick=async()=>{const meta={full_name:$('signupName').value.trim(),username:$('signupUsername').value.trim(),account_type:$('signupType').value,position:$('signupPosition').value||null,category:$('signupCategory').value||null,department:$('signupDepartment').value.trim().toUpperCase()||null};const {data,error}=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:meta}});if(error){$('authMsg').textContent=error.message;return}if(data.session){user=data.user;await enterApp()}else $('authMsg').textContent='Compte créé. Vérifie ton e-mail de confirmation.'};
async function loadPlayers(){let q=sb.from('profiles').select('id,full_name,username,avatar_url,position,category,department').eq('account_type','player').order('full_name',{ascending:true});const d=$('filterDepartment').value.trim().toUpperCase(),p=$('filterPosition').value,c=$('filterCategory').value;if(d)q=q.eq('department',d);if(p)q=q.eq('position',p);if(c)q=q.eq('category',c);const {data,error}=await q.limit(250);const root=$('playersList');if(error){root.innerHTML=`<div class="panel">${esc(error.message)}</div>`;return}if(!data?.length){root.innerHTML='<div class="panel">Aucun joueur trouvé.</div>';return}root.innerHTML=data.map(x=>`<div class="player-row" data-id="${x.id}" onclick="openPlayer('${x.id}')"><div class="player-name"><img class="mini-avatar" src="${esc(media('avatars',x.avatar_url))}" onerror="this.style.visibility='hidden'"><span>${esc(x.full_name||x.username||'Joueur')}</span></div><div>${esc(x.position||'—')}</div><div>${esc(x.category||'—')}</div><div class="arrow">›</div></div>`).join('')}
$('applyFilters').onclick=loadPlayers;$('resetFilters').onclick=()=>{$('filterDepartment').value='';$('filterPosition').value='';$('filterCategory').value='';loadPlayers()};
window.openPlayer=async id=>{selectedPlayer=id;document.querySelectorAll('.player-row').forEach(r=>r.classList.toggle('active',r.dataset.id===id));const [{data:p},{data:vids},{count:followers}]=await Promise.all([sb.from('profiles').select('*').eq('id',id).single(),sb.from('videos').select('*,likes(user_id),comments(id,user_id,body,created_at,profiles:user_id(username,full_name),comment_likes(user_id))').eq('user_id',id).order('created_at',{ascending:false}),sb.from('follows').select('*',{count:'exact',head:true}).eq('following_id',id)]);if(!p)return;const av=media('avatars',p.avatar_url);const intro=p.intro_video_path?media('footshow-videos',p.intro_video_path):'';const pane=$('profilePane');pane.innerHTML=`<div class="profile-card"><div class="profile-cover"></div><div class="profile-content"><button class="close close-mobile" onclick="closePlayer()">×</button><div class="profile-head"><img class="profile-avatar" src="${esc(av)}"><div class="profile-title"><h2>${esc(p.full_name||p.username||'Joueur')} ${p.verified?'<span class="badge">Vérifié</span>':''}</h2><p>${esc([p.position,p.category,p.club].filter(Boolean).join(' · '))}</p></div></div><div class="chips">${[p.department&&'Département '+p.department,p.city,p.level,p.foot,p.height_cm&&p.height_cm+' cm'].filter(Boolean).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><p>${esc(p.bio||'')}</p>${intro?`<div class="intro"><h3>🎥 Vidéo de présentation</h3><video controls playsinline preload="metadata" src="${esc(intro)}"></video></div>`:'<p class="msg">Aucune vidéo de présentation.</p>'}<div class="stats"><div class="stat"><b>${vids?.length||0}</b>vidéos</div><div class="stat"><b>${followers||0}</b>abonnés</div><div class="stat"><b>${esc(p.category||'—')}</b>catégorie</div></div>${id!==user.id?`<div class="profile-actions"><button class="primary" onclick="followPlayer('${id}')">+ Suivre</button>${me?.account_type==='recruiter'?`<button class="secondary" onclick="favoritePlayer('${id}')">⭐ Favori</button>`:''}</div>`:''}<div class="section-title"><h3>Meilleures actions</h3></div><div class="actions-grid">${(vids||[]).map(renderAction).join('')||'<p class="msg">Aucune action publiée.</p>'}</div></div></div>`;pane.classList.add('open')};
window.closePlayer=()=>{$('profilePane').classList.remove('open')};
function renderAction(v){const src=media('footshow-videos',v.storage_path),liked=(v.likes||[]).some(l=>l.user_id===user.id);return `<div class="action-card"><video controls playsinline preload="metadata" src="${esc(src)}"></video><div class="action-body"><b>${esc(v.action_type||'Action')}</b><small>${esc([v.opponent&&'vs '+v.opponent,v.competition].filter(Boolean).join(' · '))}</small>${v.caption?`<p>${esc(v.caption)}</p>`:''}<div class="profile-actions"><button class="secondary" onclick="toggleLike('${v.id}',${liked})">${liked?'❤️':'♡'} ${(v.likes||[]).length}</button><button class="secondary" onclick="commentOn('${v.id}')">💬 ${(v.comments||[]).length}</button></div></div></div>`}
window.toggleLike=async(id,liked)=>{const r=liked?await sb.from('likes').delete().eq('video_id',id).eq('user_id',user.id):await sb.from('likes').insert({video_id:id,user_id:user.id});if(r.error)toast(r.error.message);else openPlayer(selectedPlayer)};
window.commentOn=async id=>{const body=prompt('Écrire un commentaire');if(!body?.trim())return;const {error}=await sb.from('comments').insert({video_id:id,user_id:user.id,body:body.trim()});if(error)toast(error.message);else openPlayer(selectedPlayer)};
window.followPlayer=async id=>{const {error}=await sb.from('follows').insert({follower_id:user.id,following_id:id});if(error&&!error.message.includes('duplicate'))toast(error.message);else{toast('Joueur suivi');openPlayer(id)}};
window.favoritePlayer=async id=>{const {error}=await sb.from('recruiter_favorites').insert({recruiter_id:user.id,player_id:id});if(error&&!error.message.includes('duplicate'))toast(error.message);else toast('Ajouté aux favoris')};
function openMyProfile(){if(!me)return;$('profilePosition').value=me.position||'';$('profileCategory').value=me.category||'';$('profileDepartment').value=me.department||'';$('profileClub').value=me.club||'';$('profileCity').value=me.city||'';$('profileLevel').value=me.level||'';$('profileFoot').value=me.foot||'';$('profileHeight').value=me.height_cm||'';$('profileBio').value=me.bio||'';const av=media('avatars',me.avatar_url);$('myProfileSummary').innerHTML=`<div class="profile-head" style="margin:0"><img class="profile-avatar" src="${esc(av)}"><div class="profile-title"><h2>${esc(me.full_name||me.username||'Mon profil')}</h2><p>${esc([me.position,me.category,me.club].filter(Boolean).join(' · '))}</p></div></div>${me.intro_video_path?`<div class="intro"><video controls playsinline src="${esc(media('footshow-videos',me.intro_video_path))}"></video></div>`:''}`;$('myProfile').classList.remove('hidden');loadMyActions()}
$('closeMyProfile').onclick=()=>$('myProfile').classList.add('hidden');
async function uploadFile(bucket,file,path){const {error}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return path}
$('saveProfileBtn').onclick=async()=>{try{let avatar=me.avatar_url,intro=me.intro_video_path;const af=$('avatarFile').files[0],vf=$('introFile').files[0];if(af){const ext=af.name.split('.').pop()||'jpg';avatar=await uploadFile('avatars',af,`${user.id}/${Date.now()}.${ext}`)}if(vf){if(vf.size>80*1024*1024)throw new Error('Vidéo de présentation : 80 Mo maximum');const ext=vf.name.split('.').pop()||'mp4';intro=await uploadFile('footshow-videos',vf,`${user.id}/intro-${Date.now()}.${ext}`)}const patch={position:$('profilePosition').value||null,category:$('profileCategory').value||null,department:$('profileDepartment').value.trim().toUpperCase()||null,club:$('profileClub').value.trim()||null,city:$('profileCity').value.trim()||null,level:$('profileLevel').value.trim()||null,foot:$('profileFoot').value||null,height_cm:$('profileHeight').value?Number($('profileHeight').value):null,bio:$('profileBio').value.trim()||null,avatar_url:avatar,intro_video_path:intro};const {error}=await sb.from('profiles').update(patch).eq('id',user.id);if(error)throw error;await loadMe();openMyProfile();loadPlayers();toast('Profil enregistré')}catch(e){toast(e.message)}};
async function loadMyActions(){const {data}=await sb.from('videos').select('*').eq('user_id',user.id).order('created_at',{ascending:false});$('myActions').innerHTML=(data||[]).map(v=>`<div class="action-card"><video controls playsinline src="${esc(media('footshow-videos',v.storage_path))}"></video><div class="action-body"><b>${esc(v.action_type||'Action')}</b><small>${esc([v.opponent,v.competition].filter(Boolean).join(' · '))}</small></div></div>`).join('')||'<p class="msg">Aucune action publiée.</p>'}
$('publishActionBtn').onclick=async()=>{try{const f=$('actionFile').files[0];if(!f)throw new Error('Choisis une vidéo');if(f.size>200*1024*1024)throw new Error('200 Mo maximum');$('profileMsg').textContent='Upload en cours…';const ext=f.name.split('.').pop()||'mp4',path=await uploadFile('footshow-videos',f,`${user.id}/actions/${Date.now()}.${ext}`);const {error}=await sb.from('videos').insert({user_id:user.id,storage_path:path,action_type:$('actionType').value,opponent:$('actionOpponent').value.trim()||null,competition:$('actionCompetition').value.trim()||null,caption:$('actionCaption').value.trim()});if(error)throw error;$('profileMsg').textContent='Action ajoutée ✅';$('actionFile').value='';$('actionCaption').value='';$('actionOpponent').value='';$('actionCompetition').value='';loadMyActions();if(selectedPlayer===user.id)openPlayer(user.id)}catch(e){$('profileMsg').textContent=e.message}};
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{if(n.id==='logoutBtn')return;n.classList.add('active');document.querySelectorAll('.nav').forEach(x=>x!==n&&x.classList.remove('active'));if(n.dataset.view==='profile')openMyProfile();else if(n.dataset.view==='home'){$('myProfile').classList.add('hidden');closePlayer()}});
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
boot();