(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let canvas,ctx,running=false,score=0,timeLeft=60,streak=0,timer=null,ball={x:180,y:520,r:14},keeper={x:145,y:150,w:70,h:18,dx:2.4},target={x:60,y:115,r:22},dragStart=null;

  function openGame(){document.getElementById('gameDrawer')?.classList.remove('hidden');renderGameHome();loadGameLeaderboard();}
  function renderGameHome(){const r=document.getElementById('gameContent');if(!r)return;r.innerHTML=`<div style="font-size:12px;color:#4ade80;font-weight:900">FOOTSHOW CHALLENGE</div><h2 style="margin:4px 0 8px">🎮 Tir de précision</h2><p class="msg">Trace la trajectoire du ballon avec ton doigt. Marque, vise les cibles bonus et bats le meilleur score.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0"><div class="panel" style="text-align:center"><b style="font-size:25px">60 s</b><div class="msg">par partie</div></div><div class="panel" style="text-align:center"><b style="font-size:25px">+ bonus</b><div class="msg">lucarne & série</div></div></div><button id="startGameBtn" class="primary full">⚽ Jouer maintenant</button><div style="margin-top:18px"><h3>🏅 Meilleurs scores</h3><div id="gameLeaderboard"><div class="msg">Chargement…</div></div></div>`;document.getElementById('startGameBtn').onclick=startGame;}

  function startGame(){score=0;timeLeft=60;streak=0;running=true;const r=document.getElementById('gameContent');r.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><div><b>Score <span id="gameScore">0</span></b><div class="msg">Série <span id="gameStreak">0</span></div></div><div style="font-size:24px;font-weight:900"><span id="gameTime">60</span>s</div></div><canvas id="footballGame" width="360" height="600" style="width:100%;max-width:430px;display:block;margin:auto;background:#16763d;border-radius:20px;touch-action:none"></canvas><p class="msg" style="text-align:center">Glisse depuis le ballon vers la zone où tu veux tirer.</p><button id="quitGame" class="secondary full">Quitter la partie</button>`;canvas=document.getElementById('footballGame');ctx=canvas.getContext('2d');resetShot();bindCanvas();draw();document.getElementById('quitGame').onclick=endGame;clearInterval(timer);timer=setInterval(()=>{if(!running)return;timeLeft--;document.getElementById('gameTime').textContent=timeLeft;if(timeLeft<=0)endGame();},1000);}

  function resetShot(){ball={x:180,y:525,r:14};keeper={x:140+Math.random()*40,y:158,w:72,h:18,dx:(Math.random()>.5?1:-1)*(1.8+Math.random()*1.7)};target={x:45+Math.random()*270,y:105+Math.random()*55,r:18};dragStart=null;}
  function bindCanvas(){const pos=e=>{const rect=canvas.getBoundingClientRect(),p=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:(p.clientX-rect.left)*canvas.width/rect.width,y:(p.clientY-rect.top)*canvas.height/rect.height}};canvas.onpointerdown=e=>{const p=pos(e);if(Math.hypot(p.x-ball.x,p.y-ball.y)<45)dragStart=p;};canvas.onpointerup=e=>{if(!dragStart||!running)return;const p=pos(e),dx=p.x-dragStart.x,dy=p.y-dragStart.y;dragStart=null;if(dy>-30)return;shoot(dx,dy);};canvas.ontouchstart=e=>{e.preventDefault();const p=pos(e);if(Math.hypot(p.x-ball.x,p.y-ball.y)<45)dragStart=p;};canvas.ontouchend=e=>{e.preventDefault();if(!dragStart)return;const p=pos(e),dx=p.x-dragStart.x,dy=p.y-dragStart.y;dragStart=null;if(dy>-30)return;shoot(dx,dy);};}

  function shoot(dx,dy){const scale=0.78,destX=ball.x+dx*scale,destY=Math.max(85,ball.y+dy*scale);const steps=22;let i=0;const sx=ball.x,sy=ball.y;const a=setInterval(()=>{i++;ball.x=sx+(destX-sx)*(i/steps);ball.y=sy+(destY-sy)*(i/steps);if(i>=steps){clearInterval(a);resolveShot();}},16);}
  function resolveShot(){const inGoal=ball.x>42&&ball.x<318&&ball.y>92&&ball.y<205;const saved=ball.x>keeper.x-12&&ball.x<keeper.x+keeper.w+12&&ball.y>keeper.y-18&&ball.y<keeper.y+32;const bonus=Math.hypot(ball.x-target.x,ball.y-target.y)<target.r+ball.r;if(inGoal&&!saved){streak++;let pts=10+Math.min(streak*2,20);if(bonus)pts+=25;score+=pts;flash(bonus?`🎯 +${pts}`:`⚽ +${pts}`,'#4ade80');}else{streak=0;flash(saved?'🧤 Arrêté':'❌ Raté','#fca5a5');}document.getElementById('gameScore').textContent=score;document.getElementById('gameStreak').textContent=streak;setTimeout(resetShot,550);}
  function flash(t,c){ctx.save();ctx.fillStyle=c;ctx.font='bold 26px sans-serif';ctx.textAlign='center';ctx.fillText(t,180,300);ctx.restore();}

  function draw(){if(!running)return;ctx.clearRect(0,0,360,600);ctx.fillStyle='#178342';ctx.fillRect(0,0,360,600);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.lineWidth=3;ctx.strokeRect(35,90,290,125);ctx.strokeRect(100,90,160,62);ctx.beginPath();ctx.arc(180,455,65,Math.PI,0);ctx.stroke();ctx.fillStyle='rgba(255,255,255,.10)';for(let y=210;y<600;y+=60){ctx.fillRect(0,y,360,30)};ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.strokeRect(45,95,270,105);ctx.fillStyle='rgba(255,215,0,.35)';ctx.beginPath();ctx.arc(target.x,target.y,target.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffd54a';ctx.lineWidth=3;ctx.stroke();keeper.x+=keeper.dx;if(keeper.x<55||keeper.x+keeper.w>305)keeper.dx*=-1;ctx.fillStyle='#f2f2f2';ctx.fillRect(keeper.x,keeper.y,keeper.w,keeper.h);ctx.fillStyle='#111';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r-3,0,Math.PI*2);ctx.fill();requestAnimationFrame(draw);}

  async function endGame(){if(!running)return;running=false;clearInterval(timer);await saveBest(score);const r=document.getElementById('gameContent');r.innerHTML=`<div style="text-align:center;padding:22px"><div style="font-size:60px">🏁</div><h2>Partie terminée</h2><div style="font-size:50px;color:#4ade80;font-weight:900">${score}</div><div class="msg">points</div><button id="gameReplay" class="primary" style="margin-top:18px">Rejouer</button> <button id="gameHome" class="secondary">Classement</button></div>`;document.getElementById('gameReplay').onclick=startGame;document.getElementById('gameHome').onclick=renderGameHome;}

  async function saveBest(s){if(!window.user?.id&&typeof user==='undefined')return;const uid=(window.user?.id)||(typeof user!=='undefined'?user?.id:null);if(!uid)return;try{const {data}=await sb.from('game_scores').select('best_score').eq('user_id',uid).maybeSingle();if(!data||s>(data.best_score||0))await sb.from('game_scores').upsert({user_id:uid,best_score:s,updated_at:new Date().toISOString()});}catch(e){}
  }
  async function loadGameLeaderboard(){const root=document.getElementById('gameLeaderboard')||document.getElementById('homeGameLeaderboard');if(!root)return;try{const {data,error}=await sb.from('game_scores').select('user_id,best_score,profiles:user_id(full_name,username)').order('best_score',{ascending:false}).limit(10);if(error)throw error;if(!data?.length){root.innerHTML='<div class="msg">Aucun score pour le moment.</div>';return;}root.innerHTML=data.map((x,i)=>`<div style="display:flex;gap:10px;align-items:center;padding:8px 0;border-bottom:1px solid #20372a"><b style="width:28px">${i===0?'🥇':i===1?'🥈':i===2?'🥉':'#'+(i+1)}</b><span style="flex:1">${esc(x.profiles?.full_name||x.profiles?.username||'Joueur')}</span><b style="color:#4ade80">${x.best_score}</b></div>`).join('');}catch(e){root.innerHTML='<div class="msg">Classement disponible après activation Supabase.</div>';}}

  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('gameNav')?.addEventListener('click',openGame);document.getElementById('homeGameBtn')?.addEventListener('click',openGame);document.getElementById('closeGame')?.addEventListener('click',()=>{running=false;clearInterval(timer);document.getElementById('gameDrawer')?.classList.add('hidden')});setTimeout(loadGameLeaderboard,1600);});
})();