import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.0/build/three.module.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const games=[
  {id:'shoot',icon:'⚽',title:'Tirs de précision',tag:'ADRESSE',desc:'Évite le gardien et vise les lucarnes.'},
  {id:'free',icon:'🥅',title:'Coups francs',tag:'TECHNIQUE',desc:'Contourne le mur et trouve la lucarne.'},
  {id:'penalty',icon:'🧤',title:'Penalty Rush',tag:'SANG-FROID',desc:'Enchaîne les penalties face à un gardien rapide.'},
  {id:'targets',icon:'🎯',title:'Target Master',tag:'PRÉCISION',desc:'Touche un maximum de cibles avant la fin du chrono.'}
];
let renderer,scene,camera,ball,keeper,goal,targetMeshes=[],wall=[],stadium=[],running=false,mode='shoot',score=0,combo=0,timeLeft=45,timer=null,animId=null,startPointer=null,shooting=false,clock=new THREE.Clock(),targetPoint=new THREE.Vector3();
const BALL_START=new THREE.Vector3(0,.32,4.6),GOAL_Z=-9;

function openGame(){document.getElementById('gameDrawer')?.classList.remove('hidden');renderArcade();loadLeaderboard();}

function renderArcade(){stopGame();const r=document.getElementById('gameContent');if(!r)return;r.innerHTML=`<style>
.arcHero{padding:24px 18px;border-radius:28px;background:radial-gradient(circle at 82% 0,#20c96855,transparent 38%),linear-gradient(145deg,#102d1e,#050b08);border:1px solid #28543b;box-shadow:0 18px 50px #0008}.arcTitle{font-size:34px;line-height:1;font-weight:1000;margin:5px 0}.arcTitle span{color:#49e487}.arcGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.gameCard{position:relative;text-align:left;padding:16px;border-radius:22px;border:1px solid #294c39;background:linear-gradient(160deg,#193522,#07110b 72%);color:white;min-height:165px;overflow:hidden;box-shadow:inset 0 1px #ffffff12,0 12px 26px #0006}.gameCard:before{content:'';position:absolute;inset:auto -35px -55px auto;width:120px;height:120px;border-radius:50%;background:#44e68122;filter:blur(2px)}.gameCard:active{transform:scale(.98)}.gameIcon{font-size:40px;filter:drop-shadow(0 5px 7px #0008)}.gameTag{font-size:9px;letter-spacing:1.3px;color:#4ade80;font-weight:900}.gameCard h3{margin:7px 0 5px;font-size:17px}.gameCard p{margin:0;color:#a8b8ad;font-size:12px;line-height:1.35}.playPill{position:absolute;right:12px;bottom:12px;background:#42df7d;color:#06140c;border-radius:99px;padding:6px 10px;font-size:11px;font-weight:900}.arcRank{margin-top:18px;padding:15px;border-radius:20px;background:#07110b;border:1px solid #203c2c}.threeBadge{display:inline-flex;align-items:center;gap:6px;background:#ffffff10;border:1px solid #ffffff14;border-radius:999px;padding:5px 9px;font-size:10px;color:#cbe8d3;margin-top:10px}@media(max-width:420px){.gameCard{min-height:174px;padding:13px}.arcTitle{font-size:30px}}</style>
<div class="arcHero"><div class="gameTag">FOOTSHOW ARCADE 3D</div><div class="arcTitle">Joue. Marque. <span>Domine.</span></div><div class="msg">4 mini-jeux en 3D, pensés pour le téléphone.</div><div class="threeBadge">◈ Terrain 3D · caméra immersive · gardien animé</div><div class="arcGrid">${games.map(g=>`<button class="gameCard" data-game="${g.id}"><div class="gameIcon">${g.icon}</div><div class="gameTag">${g.tag}</div><h3>${g.title}</h3><p>${g.desc}</p><span class="playPill">JOUER ▶</span></button>`).join('')}</div><div class="arcRank"><b>🏆 CLASSEMENT FOOTSHOW ARCADE</b><div id="gameLeaderboard" style="margin-top:8px"><div class="msg">Chargement…</div></div></div></div>`;r.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>startGame(b.dataset.game));}

function startGame(id){mode=id;score=0;combo=0;timeLeft=id==='penalty'?40:45;running=true;shooting=false;const g=games.find(x=>x.id===id),r=document.getElementById('gameContent');r.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px"><div><div style="font-size:10px;color:#4ade80;font-weight:900;letter-spacing:1px">3D · ${g.tag}</div><b style="font-size:20px">${g.icon} ${g.title}</b></div><div style="text-align:right"><b style="font-size:25px;color:#4ade80" id="gameScore">0</b><div class="msg"><span id="gameTime">${timeLeft}</span>s</div></div></div><div id="threeGameWrap" style="position:relative;max-width:440px;margin:auto;border-radius:24px;overflow:hidden;border:1px solid #315d43;box-shadow:0 22px 55px #000b;background:#050b08"><div id="threeGame" style="width:100%;aspect-ratio:3/5;touch-action:none"></div><div id="gameFlash" style="pointer-events:none;position:absolute;top:18%;left:0;right:0;text-align:center;font-size:28px;font-weight:1000;text-shadow:0 3px 16px #000;opacity:0;transition:opacity .15s"></div><div style="position:absolute;bottom:10px;left:10px;right:10px;text-align:center;background:#020805aa;border:1px solid #ffffff16;border-radius:999px;padding:8px;color:#d8eadf;font-size:11px">Glisse vers le but pour tirer</div></div><button id="quitGame" class="secondary full" style="margin-top:10px">← Retour aux jeux</button>`;init3D();document.getElementById('quitGame').onclick=renderArcade;clearInterval(timer);timer=setInterval(()=>{if(!running)return;timeLeft--;const e=document.getElementById('gameTime');if(e)e.textContent=timeLeft;if(timeLeft<=0)endGame();},1000);}

function init3D(){const host=document.getElementById('threeGame');if(!host)return;scene=new THREE.Scene();scene.background=new THREE.Color(0x07120d);scene.fog=new THREE.Fog(0x07120d,18,34);camera=new THREE.PerspectiveCamera(48,3/5,.1,80);camera.position.set(0,4.6,12.3);camera.lookAt(0,1.5,-5.8);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);buildLights();buildPitch();buildGoal();buildStadium();buildBall();buildKeeper();if(mode==='free')buildWall();buildTargets();bindInput(renderer.domElement);clock.start();animate();}

function buildLights(){scene.add(new THREE.HemisphereLight(0xbfe3ff,0x16351e,2.2));const key=new THREE.DirectionalLight(0xffffff,4.2);key.position.set(-6,12,7);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-12;key.shadow.camera.right=12;key.shadow.camera.top=14;key.shadow.camera.bottom=-14;scene.add(key);const rim=new THREE.PointLight(0x59ff9a,10,30);rim.position.set(8,8,-5);scene.add(rim);}
function buildPitch(){const grass=new THREE.Mesh(new THREE.PlaneGeometry(18,36),new THREE.MeshStandardMaterial({color:0x11743b,roughness:.92}));grass.rotation.x=-Math.PI/2;grass.position.z=-4;grass.receiveShadow=true;scene.add(grass);for(let z=11;z>-21;z-=4){const stripe=new THREE.Mesh(new THREE.PlaneGeometry(18,2),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.035}));stripe.rotation.x=-Math.PI/2;stripe.position.set(0,.012,z);scene.add(stripe);}const lineMat=new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.85});const box=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-5,.03,-9),new THREE.Vector3(-5,.03,-3),new THREE.Vector3(5,.03,-3),new THREE.Vector3(5,.03,-9)]);scene.add(new THREE.Line(box,lineMat));const spot=new THREE.Mesh(new THREE.CircleGeometry(.08,16),new THREE.MeshBasicMaterial({color:0xffffff}));spot.rotation.x=-Math.PI/2;spot.position.set(0,.04,-4.8);scene.add(spot);}
function buildGoal(){goal=new THREE.Group();const postMat=new THREE.MeshStandardMaterial({color:0xffffff,metalness:.15,roughness:.35});const postGeo=new THREE.CylinderGeometry(.065,.065,2.55,16);const left=new THREE.Mesh(postGeo,postMat),right=left.clone();left.position.set(-3.1,1.28,GOAL_Z);right.position.set(3.1,1.28,GOAL_Z);const cross=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,6.2,16),postMat);cross.rotation.z=Math.PI/2;cross.position.set(0,2.55,GOAL_Z);[left,right,cross].forEach(m=>{m.castShadow=true;goal.add(m)});const netMat=new THREE.MeshBasicMaterial({color:0xcceedd,wireframe:true,transparent:true,opacity:.15});const net=new THREE.Mesh(new THREE.BoxGeometry(6.2,2.5,1.65,10,5,3),netMat);net.position.set(0,1.25,GOAL_Z-.78);goal.add(net);scene.add(goal);}
function buildStadium(){stadium=[];const standMat=new THREE.MeshStandardMaterial({color:0x15231b,roughness:1});for(const x of [-8.5,8.5]){const s=new THREE.Mesh(new THREE.BoxGeometry(3,6,26),standMat);s.position.set(x,2.5,-5);scene.add(s);stadium.push(s);}const back=new THREE.Mesh(new THREE.BoxGeometry(18,5,3),standMat);back.position.set(0,2.4,-15);scene.add(back);for(let i=0;i<90;i++){const c=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.12),new THREE.MeshBasicMaterial({color:new THREE.Color().setHSL(Math.random(),.45,.55)}));c.position.set((Math.random()-.5)*16,1.2+Math.random()*3.7,-12-Math.random()*2);scene.add(c);stadium.push(c);}for(const x of [-7,7]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.05,.08,10,10),new THREE.MeshStandardMaterial({color:0x59645d}));pole.position.set(x,5,-7);scene.add(pole);const lamp=new THREE.PointLight(0xffffff,9,22);lamp.position.set(x,10,-7);scene.add(lamp);}}
function buildBall(){const mat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.5,metalness:0});ball=new THREE.Mesh(new THREE.SphereGeometry(.32,32,20),mat);ball.position.copy(BALL_START);ball.castShadow=true;scene.add(ball);const patchMat=new THREE.MeshStandardMaterial({color:0x111111,roughness:.7});for(let i=0;i<6;i++){const p=new THREE.Mesh(new THREE.CircleGeometry(.07,5),patchMat);const a=i/6*Math.PI*2;p.position.set(Math.cos(a)*.30,.02+Math.sin(a)*.14,Math.sin(a)*.30);p.lookAt(ball.position);ball.add(p);}}
function buildKeeper(){if(mode==='targets')return;keeper=new THREE.Group();const jersey=new THREE.MeshStandardMaterial({color:mode==='penalty'?0xffb300:0x3b82f6,roughness:.65});const skin=new THREE.MeshStandardMaterial({color:0xc88b65,roughness:.8});const body=new THREE.Mesh(new THREE.BoxGeometry(.75,1.05,.38),jersey);body.position.y=1.18;const head=new THREE.Mesh(new THREE.SphereGeometry(.22,16,12),skin);head.position.y=1.93;const armGeo=new THREE.CapsuleGeometry(.11,.72,4,8);for(const sx of [-1,1]){const arm=new THREE.Mesh(armGeo,jersey);arm.rotation.z=sx*1.12;arm.position.set(sx*.58,1.35,0);keeper.add(arm);}keeper.add(body,head);keeper.position.set(0,0,GOAL_Z+.45);keeper.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(keeper);}
function buildWall(){wall=[];for(let i=0;i<4;i++){const g=new THREE.Group();const jersey=new THREE.MeshStandardMaterial({color:0xe7e7e7,roughness:.7});const body=new THREE.Mesh(new THREE.BoxGeometry(.48,.9,.3),jersey);body.position.y=1.05;const head=new THREE.Mesh(new THREE.SphereGeometry(.18,12,10),new THREE.MeshStandardMaterial({color:0xb7805d}));head.position.y=1.65;g.add(body,head);g.position.set((i-1.5)*.62,0,-5.7);scene.add(g);wall.push(g);}}
function buildTargets(){targetMeshes.forEach(t=>scene.remove(t));targetMeshes=[];const count=mode==='targets'?5:1;for(let i=0;i<count;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(mode==='targets'?.38:.48,.055,10,32),new THREE.MeshStandardMaterial({color:0xffd43b,emissive:0x7a4b00,emissiveIntensity:1.3}));ring.position.set(-2.45+Math.random()*4.9,.65+Math.random()*1.55,GOAL_Z+.16);ring.userData.hit=false;scene.add(ring);targetMeshes.push(ring);}}
function bindInput(el){const p=e=>{const r=el.getBoundingClientRect(),q=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:q.clientX-r.left,y:q.clientY-r.top}};el.onpointerdown=e=>{if(!shooting)startPointer=p(e)};el.onpointerup=e=>{if(!startPointer||shooting)return;const end=p(e),dx=end.x-startPointer.x,dy=end.y-startPointer.y;startPointer=null;if(dy>-15)return;takeShot(dx,dy,el.clientWidth,el.clientHeight)};el.ontouchstart=e=>{e.preventDefault();if(!shooting)startPointer=p(e)};el.ontouchend=e=>{e.preventDefault();if(!startPointer||shooting)return;const end=p(e),dx=end.x-startPointer.x,dy=end.y-startPointer.y;startPointer=null;if(dy>-15)return;takeShot(dx,dy,el.clientWidth,el.clientHeight)}}
function takeShot(dx,dy,w,h){shooting=true;const nx=THREE.MathUtils.clamp(dx/(w*.34),-1,1),power=THREE.MathUtils.clamp(-dy/(h*.48),.25,1.25);const tx=nx*3.25,ty=THREE.MathUtils.clamp(.45+power*1.75,.5,2.65);targetPoint.set(tx,ty,GOAL_Z+.18);const start=ball.position.clone(),duration=.62,started=performance.now();const curve=mode==='free'?-nx*1.05:0;function step(now){const t=Math.min((now-started)/(duration*1000),1),ease=1-Math.pow(1-t,2);ball.position.lerpVectors(start,targetPoint,ease);ball.position.y+=Math.sin(t*Math.PI)*(mode==='free'?2.25:1.15);ball.position.x+=Math.sin(t*Math.PI)*curve;ball.rotation.x+=.26;ball.rotation.z+=.18;if(t<1)requestAnimationFrame(step);else resolveShot();}requestAnimationFrame(step);}
function resolveShot(){let pts=0,success=false,bonus=false;if(mode==='targets'){let best=null,bestD=99;for(const t of targetMeshes){if(t.userData.hit)continue;const d=Math.hypot(ball.position.x-t.position.x,ball.position.y-t.position.y);if(d<bestD){bestD=d;best=t}}if(best&&bestD<.7){best.userData.hit=true;best.material.color.set(0x61ff94);best.material.emissive.set(0x185c31);pts=25;success=true;if(targetMeshes.every(t=>t.userData.hit))setTimeout(buildTargets,300);}}else{const inGoal=Math.abs(ball.position.x)<3.05&&ball.position.y>.15&&ball.position.y<2.6;const keeperSave=keeper&&Math.abs(ball.position.x-keeper.position.x)<.72&&ball.position.y<2.25;const wallHit=mode==='free'&&Math.abs(ball.position.x)<1.55&&ball.position.y<1.95;for(const t of targetMeshes){if(Math.hypot(ball.position.x-t.position.x,ball.position.y-t.position.y)<.78)bonus=true;}if(inGoal&&!keeperSave&&!wallHit){success=true;combo++;pts=10+Math.min(combo*2,18)+(bonus?30:0);}else combo=0;}score+=pts;const s=document.getElementById('gameScore');if(s)s.textContent=score;flash(success?(bonus?'🎯 LUCARNE !':'⚽ BUT !'):(mode!=='targets'&&keeper?'🧤 ARRÊT / RATÉ':'❌ RATÉ'),success?'#59f18f':'#ff7b7b');setTimeout(()=>{ball.position.copy(BALL_START);shooting=false;if(mode!=='targets')buildTargets();},650);}
function flash(text,color){const f=document.getElementById('gameFlash');if(!f)return;f.textContent=text;f.style.color=color;f.style.opacity='1';setTimeout(()=>f.style.opacity='0',480)}
function animate(){if(!running||!renderer)return;const t=clock.getElapsedTime();if(keeper){const speed=mode==='penalty'?2.2:1.35;keeper.position.x=Math.sin(t*speed)*2.05;keeper.rotation.z=Math.sin(t*speed)*.05;}targetMeshes.forEach((m,i)=>{m.rotation.z=t*(.5+i*.08);m.scale.setScalar(1+Math.sin(t*3+i)*.06)});renderer.render(scene,camera);animId=requestAnimationFrame(animate)}
function stopGame(){running=false;shooting=false;clearInterval(timer);cancelAnimationFrame(animId);if(renderer){renderer.dispose();renderer.domElement?.remove();renderer=null;}scene=null;camera=null;ball=null;keeper=null;goal=null;targetMeshes=[];wall=[];stadium=[];}
async function endGame(){if(!running)return;running=false;clearInterval(timer);cancelAnimationFrame(animId);await saveBest(score);const g=games.find(x=>x.id===mode),r=document.getElementById('gameContent');if(renderer){renderer.dispose();renderer=null}r.innerHTML=`<div style="text-align:center;padding:35px 12px"><div style="font-size:70px">🏆</div><div style="font-size:10px;color:#4ade80;font-weight:900;letter-spacing:1px">PARTIE TERMINÉE</div><h2>${g.title}</h2><div style="font-size:64px;font-weight:1000;color:#4ade80">${score}</div><div class="msg">POINTS</div><button id="replay" class="primary" style="margin-top:20px">Rejouer</button> <button id="arcade" class="secondary">Tous les jeux</button></div>`;document.getElementById('replay').onclick=()=>startGame(mode);document.getElementById('arcade').onclick=renderArcade;}
async function saveBest(s){const uid=window.user?.id||(typeof user!=='undefined'?user?.id:null);if(!uid)return;try{const {data}=await sb.from('game_scores').select('best_score').eq('user_id',uid).maybeSingle();if(!data||s>(data.best_score||0))await sb.from('game_scores').upsert({user_id:uid,best_score:s,updated_at:new Date().toISOString()});}catch(e){}}
async function loadLeaderboard(){const root=document.getElementById('gameLeaderboard')||document.getElementById('homeGameLeaderboard');if(!root)return;try{const {data,error}=await sb.from('game_scores').select('user_id,best_score,profiles:user_id(full_name,username)').order('best_score',{ascending:false}).limit(10);if(error)throw error;root.innerHTML=data?.length?data.map((x,i)=>`<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid #ffffff12"><b style="width:30px">${['🥇','🥈','🥉'][i]||'#'+(i+1)}</b><span style="flex:1">${esc(x.profiles?.full_name||x.profiles?.username||'Joueur')}</span><b style="color:#4ade80">${x.best_score}</b></div>`).join(''):'<div class="msg">Sois le premier au classement !</div>';}catch(e){root.innerHTML='<div class="msg">Classement indisponible.</div>';}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('gameNav')?.addEventListener('click',openGame);document.getElementById('homeGameBtn')?.addEventListener('click',openGame);document.getElementById('closeGame')?.addEventListener('click',()=>{stopGame();document.getElementById('gameDrawer')?.classList.add('hidden')});setTimeout(loadLeaderboard,1600);});
