(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let running=false,timer=null,canvas,ctx,score=0,timeLeft=45,mode='shoot',raf=0,ball,keeper,target,dragStart,targets=[],combo=0;
const games=[
 {id:'shoot',icon:'⚽',title:'Tirs de précision',desc:'Frappe, évite le gardien et vise les lucarnes.',tag:'ADRESSE'},
 {id:'free',icon:'🥅',title:'Coups francs',desc:'Contourne le mur et trouve la lucarne.',tag:'TECHNIQUE'},
 {id:'penalty',icon:'🧤',title:'Penalty Rush',desc:'Enchaîne les penalties face à un gardien rapide.',tag:'SANG-FROID'},
 {id:'targets',icon:'🎯',title:'Target Master',desc:'Touche un maximum de cibles avant la fin du chrono.',tag:'PRÉCISION'}
];
function openGame(){document.getElementById('gameDrawer')?.classList.remove('hidden');renderArcade();loadLeaderboard();}
function renderArcade(){running=false;clearInterval(timer);cancelAnimationFrame(raf);const r=document.getElementById('gameContent');if(!r)return;r.innerHTML=`<style>
.arcHero{padding:24px 18px;border-radius:28px;background:radial-gradient(circle at 80% 0,#20c96855,transparent 38%),linear-gradient(145deg,#102d1e,#050b08);border:1px solid #28543b;box-shadow:0 18px 50px #0008;overflow:hidden}.arcTitle{font-size:34px;line-height:1;font-weight:1000;margin:5px 0}.arcTitle span{color:#49e487}.arcGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.gameCard{position:relative;text-align:left;padding:16px;border-radius:22px;border:1px solid #294c39;background:linear-gradient(145deg,#12271b,#08110c);color:white;min-height:155px;box-shadow:inset 0 1px #ffffff0e,0 10px 24px #0005}.gameCard:active{transform:scale(.98)}.gameIcon{font-size:38px}.gameTag{font-size:9px;letter-spacing:1.3px;color:#4ade80;font-weight:900}.gameCard h3{margin:7px 0 5px;font-size:17px}.gameCard p{margin:0;color:#a8b8ad;font-size:12px;line-height:1.35}.playPill{position:absolute;right:12px;bottom:12px;background:#42df7d;color:#06140c;border-radius:99px;padding:6px 10px;font-size:11px;font-weight:900}.arcRank{margin-top:18px;padding:15px;border-radius:20px;background:#07110b;border:1px solid #203c2c}@media(max-width:420px){.arcGrid{grid-template-columns:1fr 1fr}.gameCard{min-height:165px;padding:13px}.arcTitle{font-size:30px}}
</style><div class="arcHero"><div class="gameTag">FOOTSHOW ARCADE</div><div class="arcTitle">Joue. Marque. <span>Domine.</span></div><div class="msg">4 mini-jeux de football. Fais exploser ton score et grimpe au classement.</div><div class="arcGrid">${games.map(g=>`<button class="gameCard" data-game="${g.id}"><div class="gameIcon">${g.icon}</div><div class="gameTag">${g.tag}</div><h3>${g.title}</h3><p>${g.desc}</p><span class="playPill">JOUER ▶</span></button>`).join('')}</div><div class="arcRank"><b>🏆 CLASSEMENT FOOTSHOW ARCADE</b><div id="gameLeaderboard" style="margin-top:8px"><div class="msg">Chargement…</div></div></div></div>`;r.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>startGame(b.dataset.game));}
function startGame(m){mode=m;score=0;combo=0;timeLeft=m==='penalty'?40:45;running=true;const g=games.find(x=>x.id===m),r=document.getElementById('gameContent');r.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px"><div><div style="font-size:11px;color:#4ade80;font-weight:900">${g.tag}</div><b style="font-size:20px">${g.icon} ${g.title}</b></div><div style="text-align:right"><b style="font-size:25px;color:#4ade80" id="gameScore">0</b><div class="msg"><span id="gameTime">${timeLeft}</span>s</div></div></div><canvas id="footballGame" width="360" height="600" style="width:100%;max-width:430px;display:block;margin:auto;border-radius:24px;touch-action:none;box-shadow:0 18px 45px #0009;border:1px solid #356347"></canvas><div class="msg" style="text-align:center;margin:9px">Glisse depuis le ballon vers ta cible.</div><button id="quitGame" class="secondary full">← Retour aux jeux</button>`;canvas=document.getElementById('footballGame');ctx=canvas.getContext('2d');reset();bind();draw();document.getElementById('quitGame').onclick=renderArcade;clearInterval(timer);timer=setInterval(()=>{if(!running)return;if(--timeLeft<=0)return endGame();const e=document.getElementById('gameTime');if(e)e.textContent=timeLeft},1000);}
function reset(){ball={x:180,y:525,r:14};dragStart=null;keeper={x:130+Math.random()*50,y:150,w:85,h:17,dx:(Math.random()>.5?1:-1)*(mode==='penalty'?4:2.4)};target={x:60+Math.random()*240,y:105+Math.random()*65,r:18};targets=Array.from({length:5},()=>({x:45+Math.random()*270,y:95+Math.random()*180,r:15,hit:false}));}
function bind(){const pos=e=>{const q=canvas.getBoundingClientRect(),p=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:(p.clientX-q.left)*360/q.width,y:(p.clientY-q.top)*600/q.height}};const down=e=>{const p=pos(e);if(Math.hypot(p.x-ball.x,p.y-ball.y)<55)dragStart=p};const up=e=>{if(!dragStart||!running)return;const p=pos(e),dx=p.x-dragStart.x,dy=p.y-dragStart.y;dragStart=null;if(dy<-20)shoot(dx,dy)};canvas.onpointerdown=down;canvas.onpointerup=up;canvas.ontouchstart=e=>{e.preventDefault();down(e)};canvas.ontouchend=e=>{e.preventDefault();up(e)}}
function shoot(dx,dy){const sx=ball.x,sy=ball.y;let tx=ball.x+dx*.8,ty=Math.max(80,ball.y+dy*.8);if(mode==='free')tx+=dx*.16;let i=0;const a=setInterval(()=>{i++;const t=i/24;ball.x=sx+(tx-sx)*t+(mode==='free'?Math.sin(t*Math.PI)*dx*.12:0);ball.y=sy+(ty-sy)*t;if(i>=24){clearInterval(a);resolve()}},15)}
function resolve(){let pts=0;if(mode==='targets'){const hit=targets.find(t=>!t.hit&&Math.hypot(ball.x-t.x,ball.y-t.y)<t.r+ball.r);if(hit){hit.hit=true;pts=20;combo++}else combo=0}else{const goal=ball.x>45&&ball.x<315&&ball.y>92&&ball.y<205,saved=ball.x>keeper.x-12&&ball.x<keeper.x+keeper.w+12&&ball.y>keeper.y-20&&ball.y<keeper.y+35,bonus=Math.hypot(ball.x-target.x,ball.y-target.y)<target.r+ball.r;let wall=false;if(mode==='free')wall=ball.y>205&&ball.y<300&&ball.x>105&&ball.x<255;if(goal&&!saved&&!wall){combo++;pts=10+Math.min(combo*2,20)+(bonus?25:0)}else combo=0}score+=pts;const s=document.getElementById('gameScore');if(s)s.textContent=score;setTimeout(reset,380)}
function field(){const grd=ctx.createLinearGradient(0,0,0,600);grd.addColorStop(0,'#123d24');grd.addColorStop(1,'#08723a');ctx.fillStyle=grd;ctx.fillRect(0,0,360,600);for(let y=0;y<600;y+=80){ctx.fillStyle=y%160===0?'#ffffff08':'#00000008';ctx.fillRect(0,y,360,80)}ctx.strokeStyle='#ffffffaa';ctx.lineWidth=3;ctx.strokeRect(35,88,290,130);ctx.strokeRect(102,88,156,65);ctx.beginPath();ctx.arc(180,455,65,Math.PI,0);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.strokeRect(45,95,270,108)}
function draw(){if(!running)return;field();if(mode==='targets'){targets.forEach(t=>{ctx.fillStyle=t.hit?'#ffffff22':'#ffd740aa';ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke()})}else{ctx.fillStyle='#ffd74066';ctx.beginPath();ctx.arc(target.x,target.y,target.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffd740';ctx.lineWidth=3;ctx.stroke();keeper.x+=keeper.dx;if(keeper.x<50||keeper.x+keeper.w>310)keeper.dx*=-1;ctx.fillStyle='#58a6ff';ctx.fillRect(keeper.x,keeper.y,keeper.w,keeper.h);ctx.beginPath();ctx.arc(keeper.x+keeper.w/2,keeper.y-11,11,0,Math.PI*2);ctx.fill();if(mode==='free'){ctx.fillStyle='#e8edf0';for(let x=115;x<=235;x+=30){ctx.beginPath();ctx.arc(x,240,9,0,Math.PI*2);ctx.fill();ctx.fillRect(x-6,247,12,42)}}}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(ball.x,ball.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 18px sans-serif';ctx.fillText('FOOTSHOW',14,28);raf=requestAnimationFrame(draw)}
async function endGame(){if(!running)return;running=false;clearInterval(timer);cancelAnimationFrame(raf);await saveBest(score);const r=document.getElementById('gameContent');r.innerHTML=`<div style="text-align:center;padding:35px 12px"><div style="font-size:70px">🏆</div><div class="gameTag">PARTIE TERMINÉE</div><h2>${games.find(x=>x.id===mode).title}</h2><div style="font-size:64px;font-weight:1000;color:#4ade80">${score}</div><div class="msg">POINTS</div><button id="replay" class="primary" style="margin-top:20px">Rejouer</button> <button id="arcade" class="secondary">Tous les jeux</button></div>`;document.getElementById('replay').onclick=()=>startGame(mode);document.getElementById('arcade').onclick=renderArcade}
async function saveBest(s){const uid=window.user?.id||(typeof user!=='undefined'?user?.id:null);if(!uid)return;try{const {data}=await sb.from('game_scores').select('best_score').eq('user_id',uid).maybeSingle();if(!data||s>(data.best_score||0))await sb.from('game_scores').upsert({user_id:uid,best_score:s,updated_at:new Date().toISOString()})}catch(e){}}
async function loadLeaderboard(){const root=document.getElementById('gameLeaderboard')||document.getElementById('homeGameLeaderboard');if(!root)return;try{const {data,error}=await sb.from('game_scores').select('user_id,best_score,profiles:user_id(full_name,username)').order('best_score',{ascending:false}).limit(10);if(error)throw error;root.innerHTML=data?.length?data.map((x,i)=>`<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid #ffffff12"><b style="width:30px">${['🥇','🥈','🥉'][i]||'#'+(i+1)}</b><span style="flex:1">${esc(x.profiles?.full_name||x.profiles?.username||'Joueur')}</span><b style="color:#4ade80">${x.best_score}</b></div>`).join(''):'<div class="msg">Sois le premier au classement !</div>'}catch(e){root.innerHTML='<div class="msg">Classement indisponible.</div>'}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('gameNav')?.addEventListener('click',openGame);document.getElementById('homeGameBtn')?.addEventListener('click',openGame);document.getElementById('closeGame')?.addEventListener('click',()=>{running=false;clearInterval(timer);cancelAnimationFrame(raf);document.getElementById('gameDrawer')?.classList.add('hidden')});setTimeout(loadLeaderboard,1600)});
})();