(()=>{
const days=[
{day:'Lundi',focus:'Récupération',meals:[['🥣 Petit-déjeuner','Flocons d’avoine, lait ou boisson végétale, banane, poignée d’amandes'],['🍽️ Déjeuner','Poulet grillé, riz complet, courgettes, yaourt nature'],['🍎 Collation','Pomme + fromage blanc ou skyr'],['🌙 Dîner','Saumon, pommes de terre vapeur, haricots verts, fruit']]},
{day:'Mardi',focus:'Entraînement',meals:[['🥣 Petit-déjeuner','Pain complet, œufs, fruit frais, yaourt'],['🍽️ Déjeuner','Pâtes semi-complètes, steak haché 5 %, sauce tomate, salade'],['🍌 Collation','Banane + poignée de noix'],['🌙 Dîner','Dinde, semoule, légumes rôtis, compote sans sucres ajoutés']]},
{day:'Mercredi',focus:'Énergie',meals:[['🥣 Petit-déjeuner','Porridge avoine, fruits rouges, miel, yaourt'],['🍽️ Déjeuner','Bowl quinoa, poulet, avocat, tomates, concombre'],['🥪 Collation','Tartine de pain complet + beurre de cacahuète + fruit'],['🌙 Dîner','Omelette, patate douce, salade verte, yaourt']]},
{day:'Jeudi',focus:'Puissance',meals:[['🥣 Petit-déjeuner','Muesli sans excès de sucre, lait, kiwi, œuf dur'],['🍽️ Déjeuner','Bœuf maigre, riz basmati, brocoli, fruit'],['🥛 Collation','Smoothie banane-lait-avoine ou yaourt + fruit'],['🌙 Dîner','Poisson blanc, pâtes, ratatouille, fromage blanc']]},
{day:'Vendredi',focus:'Préparation match',meals:[['🥣 Petit-déjeuner','Pain complet, miel, yaourt, banane'],['🍽️ Déjeuner','Pâtes, poulet, légumes cuits, fruit'],['🍌 Collation','Banane + compote + quelques amandes'],['🌙 Dîner','Riz blanc ou basmati, dinde, carottes/courgettes cuites, yaourt']]},
{day:'Samedi',focus:'Jour de match',meals:[['🥣 Petit-déjeuner','Pain, miel ou confiture, banane, yaourt, eau'],['🍽️ Repas avant match','3 à 4 h avant : pâtes ou riz, poulet/dinde, légumes faciles à digérer, compote'],['⚡ Collation','60 à 90 min avant si besoin : banane ou compote + eau'],['🌙 Après match','Riz/pommes de terre, poulet ou poisson, légumes, yaourt + fruit']]},
{day:'Dimanche',focus:'Repos & récupération',meals:[['🥣 Petit-déjeuner','Œufs, pain complet, fruit, yaourt'],['🍽️ Déjeuner','Poulet rôti, pommes de terre, salade variée, fruit'],['🍎 Collation','Fruit + yaourt ou poignée d’oléagineux'],['🌙 Dîner','Soupe de légumes, poisson ou œufs, pain complet, fromage blanc']]}
];
function ensure(){let d=document.getElementById('nutritionDrawer');if(d)return d;d=document.createElement('section');d.id='nutritionDrawer';d.className='drawer hidden';d.innerHTML='<div class="drawer-inner" style="max-width:760px"><button id="closeNutrition" class="close">×</button><div id="nutritionContent"></div></div>';document.body.appendChild(d);d.querySelector('#closeNutrition').onclick=()=>d.classList.add('hidden');return d}
function inject(){if(document.getElementById('openNutrition'))return;const grid=document.querySelector('.fs-v2-actions');if(!grid)return;const b=document.createElement('button');b.id='openNutrition';b.innerHTML='<span>🥗</span><b>Alimentation</b><small>Menus de la semaine</small>';b.onclick=open;grid.appendChild(b)}
function open(){const d=ensure(),r=document.getElementById('nutritionContent');d.classList.remove('hidden');r.innerHTML=`<style>.nu-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:15px}.nu-card{background:linear-gradient(145deg,#10251a,#08120d);border:1px solid #294634;border-radius:17px;padding:16px;color:#fff;text-align:left}.nu-card h3{margin:0 0 4px}.nu-card small{color:#9eb0a5}.nu-sheet{background:#0c1912;border:1px solid #294634;border-radius:18px;padding:16px;margin-top:12px}.nu-meal{padding:12px 0;border-bottom:1px solid #ffffff10}.nu-meal:last-child{border-bottom:0}.nu-tip{background:#183323;border-left:3px solid #4ade80;padding:12px;border-radius:10px;margin-top:12px}@media(max-width:560px){.nu-grid{grid-template-columns:1fr}}</style><div class="fs-v2-kicker">FOOTSHOW NUTRITION</div><h2>🥗 Alimentation</h2><div class="msg">Exemple de menus équilibrés pour une semaine de football. Les quantités dépendent de l’âge, du gabarit et du volume d’entraînement.</div><div class="nu-grid">${days.map((d,i)=>`<button class="nu-card" data-nu="${i}"><h3>${d.day}</h3><small>${d.focus}</small></button>`).join('')}</div><div class="nu-tip"><b>💧 Hydratation</b><div class="msg">Boire régulièrement dans la journée, davantage par forte chaleur ou pendant les séances. L’eau reste la boisson principale.</div></div><div class="nu-tip"><b>⚠️ À adapter</b><div class="msg">Ce planning est général et ne remplace pas les conseils d’un médecin ou d’un diététicien du sport, surtout en cas d’allergie, de problème médical ou d’objectif nutritionnel particulier.</div></div>`;r.querySelectorAll('[data-nu]').forEach(b=>b.onclick=()=>sheet(+b.dataset.nu))}
function sheet(i){const d=days[i],r=document.getElementById('nutritionContent');r.innerHTML=`<button id="nuBack" class="secondary">← Semaine</button><div class="nu-sheet"><div class="fs-v2-kicker">MENU DU JOUR</div><h2>${d.day} · ${d.focus}</h2>${d.meals.map(m=>`<div class="nu-meal"><b>${m[0]}</b><div class="msg" style="margin-top:5px">${m[1]}</div></div>`).join('')}<div class="nu-tip"><b>Conseil FootShow</b><div class="msg">Évite de tester un nouvel aliment juste avant un match. Privilégie des repas que tu digères bien et garde une hydratation régulière.</div></div></div>`;document.getElementById('nuBack').onclick=open}
window.openFootShowNutrition=open;document.addEventListener('DOMContentLoaded',()=>{let n=0;const t=setInterval(()=>{inject();if(document.getElementById('openNutrition')||++n>30)clearInterval(t)},500)});
})();