(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>window.user?.id||(typeof user!=='undefined'?user?.id:null);
let map=null,markers=[];
function ensure(){let d=document.getElementById('opportunityMapDrawer');if(d)return d;d=document.createElement('section');d.id='opportunityMapDrawer';d.className='drawer hidden';d.innerHTML='<div class="drawer-inner" style="max-width:940px"><button class="close" id="closeOpportunityMap">×</button><div id="opportunityMapContent"></div></div>';document.body.appendChild(d);d.querySelector('#closeOpportunityMap').onclick=()=>d.classList.add('hidden');return d}
async function inject(){const grid=document.querySelector('.fs-v2-actions');if(!grid||document.getElementById('openOpportunityMap'))return;const b=document.createElement('button');b.id='openOpportunityMap';b.innerHTML='<span>📍</span><b>Carte FootShow</b><small>Opportunités autour de toi</small>';b.onclick=open;grid.appendChild(b)}
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function geocode(q){if(!q)return null;const key='fsgeo:'+q.toLowerCase();try{const cached=localStorage.getItem(key);if(cached)return JSON.parse(cached)}catch(_){}try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=fr&q='+encodeURIComponent(q),{headers:{'Accept-Language':'fr'}});const arr=await res.json();if(!arr?.[0])return null;const g={lat:+arr[0].lat,lng:+arr[0].lon};try{localStorage.setItem(key,JSON.stringify(g))}catch(_){}return g}catch(_){return null}}
function km(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
async function open(){const d=ensure(),r=document.getElementById('opportunityMapContent');d.classList.remove('hidden');r.innerHTML='<div class="fs-v2-kicker">OPPORTUNITÉS</div><h2>📍 Carte FootShow</h2><div class="msg">Détections, stages et tournois autour de toi.</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin:12px 0"><select id="mapDistance" class="input" style="max-width:180px"><option value="10">10 km</option><option value="25" selected>25 km</option><option value="50">50 km</option><option value="100">100 km</option></select><input id="mapPostal" class="input" maxlength="5" placeholder="Ton code postal" style="max-width:180px"><button id="mapGo" class="primary">Afficher</button></div><div id="footshowMap" style="height:62vh;min-height:420px;border-radius:18px;overflow:hidden;background:#0a1410"></div><div id="mapList"></div>';const {data:p}=await sb.from('profiles').select('department,city').eq('id',uid()).maybeSingle();document.getElementById('mapPostal').value=p?.department||'';document.getElementById('mapGo').onclick=renderMap;await loadLeaflet();await renderMap()}
async function renderMap(){const box=document.getElementById('footshowMap'),list=document.getElementById('mapList');if(!box||!window.L)return;list.innerHTML='<div class="msg">Recherche des opportunités…</div>';const cp=document.getElementById('mapPostal').value.replace(/\D/g,'').slice(0,5),dist=+document.getElementById('mapDistance').value;const center=await geocode(cp+' France');if(!center){list.innerHTML='<div class="panel">Code postal introuvable.</div>';return}if(!map){map=L.map('footshowMap').setView([center.lat,center.lng],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(map)}else map.setView([center.lat,center.lng],10);markers.forEach(m=>m.remove());markers=[];const [d,s,t]=await Promise.all([sb.from('detections').select('id,title,event_date,postal_code,city,address,status').eq('status','open'),sb.from('stages').select('id,title,start_date,postal_code,city,address,status').eq('status','open'),sb.from('tournaments').select('id,title,event_date,postal_code,city,address,status').eq('status','open')]);const rows=[...(d.data||[]).map(x=>({...x,type:'Détection',date:x.event_date,icon:'📅'})),...(s.data||[]).map(x=>({...x,type:'Stage',date:x.start_date,icon:'🏕️'})),...(t.data||[]).map(x=>({...x,type:'Tournoi',date:x.event_date,icon:'🏟️'}))];const found=[];for(const x of rows){const g=await geocode([x.address,x.postal_code,x.city,'France'].filter(Boolean).join(' '));if(!g)continue;const distance=km(center,g);if(distance>dist)continue;found.push({...x,...g,distance});const m=L.marker([g.lat,g.lng]).addTo(map).bindPopup(`<b>${x.icon} ${esc(x.type)}</b><br>${esc(x.title)}<br>${esc(x.city||'')}<br>${distance.toFixed(1)} km`);markers.push(m)}L.circle([center.lat,center.lng],{radius:dist*1000,fillOpacity:.03}).addTo(map);list.innerHTML=found.length?`<h3 style="margin-top:14px">${found.length} opportunité(s) dans un rayon de ${dist} km</h3>`+found.sort((a,b)=>a.distance-b.distance).map(x=>`<div class="panel" style="margin-top:8px"><b>${x.icon} ${esc(x.type)} · ${esc(x.title)}</b><div class="msg">📅 ${esc(x.date||'')} · 📍 ${esc(x.city||'')} · ${x.distance.toFixed(1)} km</div></div>`).join(''):'<div class="panel" style="margin-top:12px">Aucune opportunité trouvée dans ce rayon.</div>'}
window.openFootShowMap=open;document.addEventListener('DOMContentLoaded',()=>{let n=0;const t=setInterval(()=>{inject();if(document.getElementById('openOpportunityMap')||++n>30)clearInterval(t)},600)});
})();