(()=>{
  const THEMES={
    general:{title:'Football général',icon:'⚽',questions:[
      ['Combien de joueurs une équipe aligne-t-elle au coup d’envoi ?',['9','11','12'],1],['Quelle partie du corps un joueur de champ ne peut-il normalement pas utiliser volontairement ?',['La tête','La poitrine','La main ou le bras'],2],['Combien de mi-temps compte un match classique ?',['2','3','4'],0],['Quelle est la durée réglementaire d’un match senior ?',['80 min','90 min','100 min'],1],['Quel joueur porte généralement une couleur différente ?',['Le capitaine','Le gardien','L’avant-centre'],1],['Comment appelle-t-on trois buts du même joueur ?',['Un triplé','Un doublé','Un clean sheet'],0],['Quel poste joue le plus près du but adverse ?',['Avant-centre','Défenseur central','Gardien'],0],['Que signifie clean sheet ?',['Aucun carton','Aucun but encaissé','Aucune faute'],1],['Quel est un rôle majeur de l’arbitre assistant ?',['Conseiller l’entraîneur','Aider sur hors-jeu et sorties','Compter les tirs'],1],['Combien de points rapporte une victoire ?',['1','2','3'],2],['Combien de points rapporte un nul ?',['0','1','2'],1],['Comment appelle-t-on un joueur qui organise le jeu offensif ?',['Meneur de jeu','Ramasseur','Arbitre assistant'],0],['Une passe qui mène directement à un but est une…',['Passe neutre','Passe décisive','Passe de sécurité'],1],['Où se trouve le point de penalty ?',['Rond central','Surface de réparation','Zone technique'],1],['À quelle distance du but se situe le point de penalty ?',['9 m','11 m','13 m'],1],['Un but marqué contre son propre camp est un…',['But en or','CSC','But indirect'],1],['Qui peut prendre le ballon à la main dans sa surface ?',['Le gardien','Tout défenseur','Le capitaine'],0],['Après une sortie en ligne de touche, on reprend par…',['Une touche','Un corner','Un coup franc'],0],['Un duel attaquant-gardien s’appelle souvent…',['Un un-contre-un','Un bloc médian','Un coup d’envoi'],0],['Que trouve-t-on aux quatre coins du terrain ?',['Drapeaux de corner','Panneaux obligatoires','Mini-buts'],0]
    ]},
    worldcup:{title:'Coupe du monde',icon:'🌍',questions:[
      ['Qui a remporté la Coupe du monde 2022 ?',['Argentine','France','Brésil'],0],['Où s’est jouée la Coupe du monde 2022 ?',['Qatar','Russie','Émirats arabes unis'],0],['Qui a gagné en 2018 ?',['Croatie','France','Allemagne'],1],['Qui a gagné en 2014 ?',['Argentine','Allemagne','Espagne'],1],['Qui a gagné en 2010 ?',['Espagne','Pays-Bas','Italie'],0],['Qui a gagné en 2006 ?',['France','Italie','Brésil'],1],['Qui a remporté la première édition en 1930 ?',['Uruguay','Argentine','Italie'],0],['Qui a marqué un triplé en finale 2022 ?',['Messi','Mbappé','Di María'],1],['Qui a perdu la finale 2022 ?',['France','Croatie','Maroc'],0],['Qui a fini troisième en 2022 ?',['Maroc','Croatie','Pays-Bas'],1],['Quelle nation compte cinq titres mondiaux ?',['Brésil','Allemagne','Italie'],0],['Qui a accueilli le Mondial 2014 ?',['Afrique du Sud','Brésil','Allemagne'],1],['Qui a accueilli le Mondial 2010 ?',['Afrique du Sud','Égypte','Maroc'],0],['Qui a été élu meilleur joueur du Mondial 2022 ?',['Messi','Álvarez','Martínez'],0],['Qui a obtenu le Gant d’or 2022 ?',['Lloris','Emiliano Martínez','Bounou'],1],['Qui a éliminé le Brésil en quarts en 2022 ?',['Croatie','Argentine','France'],0],['Qui a éliminé l’Espagne en huitièmes en 2022 ?',['Portugal','Maroc','Croatie'],1],['Qui a été champion du monde en 1998 ?',['France','Brésil','Italie'],0],['Qui a gagné en 1958, 1962, 1970, 1994 et 2002 ?',['Allemagne','Brésil','Argentine'],1],['En cas d’égalité après 90 min en phase à élimination directe, que peut-il se passer ?',['Le mieux classé gagne','Prolongation','Match toujours rejoué'],1]
    ]},
    ucl:{title:'Ligue des champions',icon:'⭐',questions:[
      ['Qui a gagné la C1 2021-2022 ?',['Real Madrid','Liverpool','Manchester City'],0],['Qui a gagné en 2022-2023 ?',['Inter','Manchester City','Real Madrid'],1],['Qui a gagné en 2019-2020 ?',['Bayern','PSG','Chelsea'],0],['Qui a gagné en 2020-2021 ?',['Manchester City','Chelsea','Bayern'],1],['Qui a battu Liverpool en finale 2018 ?',['Real Madrid','Juventus','Bayern'],0],['Quel club détient historiquement le record de titres ?',['AC Milan','Real Madrid','Liverpool'],1],['Quel club français a gagné en 1993 ?',['PSG','OM','Monaco'],1],['Qui a gagné en 2015 ?',['Barcelone','Juventus','Real Madrid'],0],['Qui a gagné en 2013 ?',['Dortmund','Bayern','Chelsea'],1],['Qui a gagné en 2012 ?',['Chelsea','Bayern','Manchester United'],0],['Qui a gagné en 2009 ?',['Manchester United','Barcelone','Inter'],1],['Qui a gagné en 2010 ?',['Inter','Bayern','Barcelone'],0],['Qui entraînait l’Inter en 2010 ?',['Mourinho','Guardiola','Ancelotti'],0],['Qui a gagné la finale 2005 après avoir remonté l’AC Milan ?',['Liverpool','Arsenal','Chelsea'],0],['Où se trouve le Bernabéu ?',['Madrid','Barcelone','Séville'],0],['Quel club joue à Anfield ?',['Liverpool','Manchester United','Arsenal'],0],['Quel club joue à l’Allianz Arena ?',['Dortmund','Bayern','Leipzig'],1],['Quel club partage San Siro avec l’Inter ?',['AC Milan','Juventus','Napoli'],0],['Qui a gagné en 2006 ?',['Arsenal','Barcelone','AC Milan'],1],['Qui a gagné trois C1 de suite en 2016, 2017 et 2018 ?',['Real Madrid','Barcelone','Bayern'],0]
    ]},
    national:{title:'Équipe nationale',icon:'🇲🇦',questions:[
      ['Jusqu’à quel tour le Maroc est-il allé au Mondial 2022 ?',['Quart','Demi-finale','Finale'],1],['Qui était sélectionneur du Maroc au Mondial 2022 ?',['Walid Regragui','Hervé Renard','Vahid Halilhodžić'],0],['Quel gardien était titulaire au Mondial 2022 ?',['Munir','Yassine Bounou','Anas Zniti'],1],['Qui était capitaine principal du Maroc au Mondial 2022 ?',['Hakimi','Romain Saïss','Amrabat'],1],['Qui le Maroc a-t-il éliminé aux tirs au but en huitièmes en 2022 ?',['Espagne','Portugal','Belgique'],0],['Qui a inscrit le tir au but décisif face à l’Espagne ?',['Ziyech','Hakimi','En-Nesyri'],1],['Qui le Maroc a-t-il battu 1-0 en quart de finale ?',['Portugal','France','Croatie'],0],['Qui a marqué contre le Portugal en quart ?',['En-Nesyri','Boufal','Ounahi'],0],['Qui a éliminé le Maroc en demi-finale ?',['Argentine','France','Croatie'],1],['Qui a affronté le Maroc pour la 3e place ?',['Croatie','Pays-Bas','Portugal'],0],['Dans quel groupe était le Maroc en 2022 ?',['Groupe F','Groupe C','Groupe H'],0],['Quelle équipe était dans son groupe ?',['Belgique','Espagne','Sénégal'],0],['Quelle autre équipe était dans ce groupe ?',['Canada','Brésil','Uruguay'],0],['Quelle troisième équipe complétait le groupe ?',['Croatie','Suisse','Serbie'],0],['À quelle place le Maroc a-t-il fini son groupe ?',['1er','2e','3e'],0],['Quel exploit le Maroc a-t-il réalisé en 1986 ?',['Premier pays africain en huitièmes','Premier champion africain','Premier hôte africain'],0],['Quelle compétition continentale le Maroc a-t-il gagnée en 1976 ?',['CAN','Coupe arabe','Coupe des confédérations'],0],['Quel est le surnom courant de la sélection marocaine ?',['Lions de l’Atlas','Aigles de Carthage','Éléphants'],0],['Qui a marqué contre le Canada au Mondial 2022 ?',['Hakim Ziyech','Amrabat','Mazraoui'],0],['Quel joueur marocain a remporté la Serie A 2020-2021 avec l’Inter ?',['Achraf Hakimi','Hakim Ziyech','Yassine Bounou'],0]
    ]},
    rules:{title:'Règles du jeu',icon:'🟨',questions:[
      ['Quel carton exclut immédiatement ?',['Jaune','Rouge','Blanc'],1],['Deux jaunes au même joueur donnent normalement…',['Une exclusion','Un avertissement simple','Un penalty'],0],['Une touche se joue avec…',['Les deux mains','Un pied','La tête'],0],['Le ballon est lancé en touche…',['Depuis derrière et au-dessus de la tête','Depuis la poitrine','Au pied'],0],['Peut-on être hors-jeu directement sur une touche ?',['Oui','Non','Seulement dans sa surface'],1],['Peut-on être hors-jeu directement sur un corner ?',['Oui','Non','Seulement si attaquant'],1],['Peut-on être hors-jeu directement sur un coup de pied de but ?',['Oui','Non','Seulement après la 60e'],1],['Si un défenseur touche en dernier avant sortie par la ligne de but, sans but, qui obtient le corner ?',['Attaquants','Défenseurs','Arbitre choisit'],0],['Si un attaquant touche en dernier avant sortie par la ligne de but, sans but, qui reprend ?',['Défense avec coup de pied de but','Attaque avec corner','Touche'],0],['Un penalty est tiré depuis…',['Le point de penalty','Le rond central','La ligne des 6 m'],0],['Le gardien peut-il prendre à la main une passe volontaire au pied d’un coéquipier ?',['Oui toujours','Non en principe','Seulement en corner'],1],['L’arbitre peut-il laisser l’avantage après une faute ?',['Oui','Non','Seulement après un but'],0],['Un but est valable si le ballon franchit entièrement la ligne entre les poteaux et sous la barre ?',['Oui','Non','Seulement si puissant'],0],['Le coup d’envoi se joue depuis…',['Le rond central','La surface','Le corner'],0],['Un coup franc direct peut-il entrer directement dans le but adverse ?',['Oui','Non','Seulement après touche'],0],['Sur un coup franc indirect, le ballon doit-il toucher un autre joueur avant un but valable ?',['Oui','Non','Seulement le gardien'],0],['Un joueur blessé peut-il parfois être autorisé à quitter le terrain pour soins ?',['Oui','Non jamais','Seulement le capitaine'],0],['Qui décide du temps additionnel ?',['L’arbitre','Le public','Le capitaine'],0],['Un remplaçant doit-il entrer sans autorisation de l’arbitre ?',['Oui','Non','Seulement à domicile'],1],['Un joueur peut-il marquer directement sur un corner ?',['Oui','Non','Seulement de la tête'],0]
    ]}
  };
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let active=null,index=0,score=0;
  function openQuizHome(){document.getElementById('quizDrawer')?.classList.remove('hidden');renderThemes();loadLeaderboard();}
  function renderThemes(){const r=document.getElementById('quizContent');if(!r)return;r.innerHTML=`<div style="font-size:12px;color:#4ade80;font-weight:900">FOOTSHOW QUIZ</div><h2 style="margin:4px 0 8px">🧠 Quiz</h2><p class="msg">20 questions par thème · 3 choix · 1 point par bonne réponse.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px">${Object.entries(THEMES).map(([k,t])=>`<button data-theme="${k}" style="text-align:left;background:#0d1b14;border:1px solid #294734;color:#fff;border-radius:16px;padding:16px"><div style="font-size:32px">${t.icon}</div><b style="display:block;font-size:17px;margin:6px 0">${esc(t.title)}</b><span class="msg">20 questions</span></button>`).join('')}</div>`;r.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>startQuiz(b.dataset.theme));}
  function startQuiz(k){active=k;index=0;score=0;renderQuestion();}
  function renderQuestion(){const t=THEMES[active],q=t.questions[index],r=document.getElementById('quizContent');r.innerHTML=`<button id="quizBack" class="secondary">← Thèmes</button><div style="margin:18px 0 8px;color:#4ade80;font-weight:900">${esc(t.title)} · ${index+1}/20</div><h2 style="font-size:24px">${esc(q[0])}</h2><div style="display:grid;gap:10px;margin-top:18px">${q[1].map((a,i)=>`<button class="secondary quiz-answer" data-answer="${i}" style="text-align:left;padding:14px">${String.fromCharCode(65+i)}. ${esc(a)}</button>`).join('')}</div><div class="msg" style="margin-top:14px">Score actuel : ${score}</div>`;document.getElementById('quizBack').onclick=renderThemes;r.querySelectorAll('.quiz-answer').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));}
  function answer(a){const q=THEMES[active].questions[index];if(a===q[2])score++;index++;if(index<20)renderQuestion();else finish();}
  async function finish(){const t=THEMES[active],r=document.getElementById('quizContent');r.innerHTML=`<div style="text-align:center;padding:20px"><div style="font-size:56px">${score>=16?'🏆':score>=12?'👏':'⚽'}</div><h2>${esc(t.title)}</h2><div style="font-size:46px;font-weight:900;color:#4ade80">${score}/20</div><p class="msg">Ton meilleur score est enregistré dans le classement.</p><button id="quizAgain" class="primary">Rejouer</button> <button id="quizThemes" class="secondary">Autres thèmes</button></div>`;document.getElementById('quizAgain').onclick=()=>startQuiz(active);document.getElementById('quizThemes').onclick=renderThemes;try{const uid=user?.id;if(uid){const {data}=await sb.from('quiz_scores').select('score').eq('user_id',uid).eq('theme',active).maybeSingle();if(!data||score>data.score)await sb.from('quiz_scores').upsert({user_id:uid,theme:active,score,updated_at:new Date().toISOString()});}loadLeaderboard();}catch(e){} }
  async function loadLeaderboard(){const root=document.getElementById('quizLeaderboard');if(!root)return;const {data,error}=await sb.from('quiz_scores').select('user_id,theme,score,profiles:user_id(full_name,username,avatar_url)');if(error){root.innerHTML='<div class="msg">Classement disponible après activation de la table quiz_scores.</div>';return;}const totals=new Map();for(const s of data||[]){const p=s.profiles||{};if(!totals.has(s.user_id))totals.set(s.user_id,{name:p.full_name||p.username||'Joueur',avatar:p.avatar_url,total:0});totals.get(s.user_id).total+=s.score;}const arr=[...totals.values()].sort((a,b)=>b.total-a.total).slice(0,10);root.innerHTML=arr.length?arr.map((x,i)=>`<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid #20372a"><b style="width:28px">${i===0?'🥇':i===1?'🥈':i===2?'🥉':'#'+(i+1)}</b><img src="${esc(x.avatar?media('avatars',x.avatar):'')}" style="width:34px;height:34px;border-radius:50%;object-fit:cover;background:#203329"><div style="flex:1;font-weight:800">${esc(x.name)}</div><b style="color:#4ade80">${x.total} pts</b></div>`).join(''):'<div class="msg">Aucun score pour le moment.</div>';}
  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('quizNav')?.addEventListener('click',openQuizHome);document.getElementById('homeQuizBtn')?.addEventListener('click',openQuizHome);document.getElementById('closeQuiz')?.addEventListener('click',()=>document.getElementById('quizDrawer').classList.add('hidden'));setTimeout(loadLeaderboard,1400);});
})();