(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>window.user?.id||(typeof user!=='undefined'?user?.id:null);
function ensureUi(){
 if(document.getElementById('stagesDrawer'))return;
 const actions=document.querySelector('.fs-v2-actions');
 if(actions&&!document.getElementById('openStagesV2')){
   const b=document.createElement('button');b.id='openStagesV2';b.innerHTML='<span>🏕️</span><b>Stages</b><small>Stages de football</small>';actions.appendChild(b);
 }
 document.body.insertAdjacentHTML('beforeend',`<section id="stagesDrawer" class="drawer hidden"><div class="drawer-inner" style="max-width:720px"><button id="closeStages" class="close">×</button><div class="fs-v2-kicker">FOOTSHOW</div><h2>🏕️ Stages de football</h2><p class="msg">Trouve un stage ou publie une nouvelle session.</p><div id="stagePublisher"></div><div class="panel" style="margin:12px 0"><div class="two"><div><label>Code postal</label><input id="stageFilterPostal" class="input" maxlength="5" inputmode="numeric" placeholder="Ex. 73000"></div><div><label>Catégorie</label><select id="stageFilterCategory" class="input category-select"></select></div></div><button id="stageFilterBtn" class="secondary full">Filtrer les stages</button></div><div id="stagesList"><div class="msg">Chargement…</div></div></div></section>`);
 document.getElementById('closeStages').onclick=()=>document.getElementById('stagesDrawer').classList.add('hidden');
 document.getElementById('stageFilterBtn').onclick=loadStages;
 document.getElementById('openStagesV2')?.addEventListener('click',openStages);
 setTimeout(()=>{if(typeof fillSelects==='function')fillSelects()},50);
}
async function openStages(){ensureUi();document.getElementById('stagesDrawer').classList.remove('hidden');await renderPublisher();await loadStages();}
async function renderPublisher(){const root=document.getElementById('stagePublisher');if(!root)return;let p=null;try{const {data}=await sb.from('profiles').select('account_type,full_name,username,club').eq('id',uid()).single();p=data}catch{}
 const canPublish=p?.account_type==='recruiter';
 if(!canPublish){root.innerHTML='<div class="panel"><b>ℹ️ Publication réservée aux clubs / recruteurs</b><div class="msg">Les joueurs peuvent consulter les stages et contacter l’organisateur.</div></div>';return}
 root.innerHTML=`<div class="panel"><b>➕ Publier un stage</b><div class="two" style="margin-top:10px"><div><label>Nom du stage</label><input id="stageTitle" class="input" placeholder="Stage vacances de Toussaint"></div><div><label>Organisateur / club</label><input id="stageClub" class="input" value="${esc(p.club||p.full_name||p.username||'')}"></div></div><div class="two"><div><label>Date de début</label><input id="stageDate" type="date" class="input"></div><div><label>Durée</label><input id="stageDuration" class="input" placeholder="3 jours / 1 semaine"></div></div><label>Lieu</label><input id="stagePlace" class="input" placeholder="Stade, complexe sportif…"><div class="two"><div><label>Ville</label><input id="stageCity" class="input"></div><div><label>Code postal</label><input id="stagePostal" class="input" maxlength="5" inputmode="numeric"></div></div><div class="two"><div><label>Prix (€)</label><input id="stagePrice" type="number" min="0" step="0.01" class="input" placeholder="150"></div><div><label>Catégories</label><input id="stageCategories" class="input" placeholder="U12, U13, U14"></div></div><label>Description</label><textarea id="stageDescription" class="input" rows="3" placeholder="Programme, horaires, repas, équipement…"></textarea><div class="two"><div><label>Email de contact</label><input id="stageEmail" type="email" class="input"></div><div><label>Téléphone</label><input id="stagePhone" type="tel" class="input"></div></div><button id="publishStage" class="primary full">Publier le stage</button><p id="stageMsg" class="msg"></p></div>`;
 document.getElementById('publishStage').onclick=publishStage;
}
async function publishStage(){const msg=document.getElementById('stageMsg');const title=document.getElementById('stageTitle').value.trim(),club=document.getElementById('stageClub').value.trim(),event_date=document.getElementById('stageDate').value,duration=document.getElementById('stageDuration').value.trim(),place=document.getElementById('stagePlace').value.trim(),city=document.getElementById('stageCity').value.trim();if(!title||!club||!event_date||!duration||!place||!city){msg.textContent='Complète le nom, la date, la durée et le lieu.';return}const categories=document.getElementById('stageCategories').value.split(',').map(x=>x.trim()).filter(Boolean);const priceRaw=document.getElementById('stagePrice').value;const {error}=await sb.from('stages').insert({club_id:uid(),club_name:club,title,event_date,duration,place,city,postal_code:document.getElementById('stagePostal').value.trim()||null,price:priceRaw?Number(priceRaw):0,categories,description:document.getElementById('stageDescription').value.trim()||null,contact_email:document.getElementById('stageEmail').value.trim()||null,contact_phone:document.getElementById('stagePhone').value.trim()||null});if(error){msg.textContent=error.message;return}msg.textContent='Stage publié ✅';await loadStages();}
async function loadStages(){const root=document.getElementById('stagesList');if(!root)return;root.innerHTML='<div class="msg">Chargement…</div>';const postal=document.getElementById('stageFilterPostal')?.value.trim()||'',cat=document.getElementById('stageFilterCategory')?.value||'';let q=sb.from('stages').select('*').eq('status','open').gte('event_date',new Date().toISOString().slice(0,10)).order('event_date',{ascending:true}).limit(100);if(postal)q=q.eq('postal_code',postal);if(cat)q=q.contains('categories',[cat]);const {data,error}=await q;if(error){root.innerHTML='<div class="panel"><div class="msg">La table des stages doit être activée dans Supabase.</div></div>';return}root.innerHTML=(data||[]).map(s=>`<article class="panel" style="margin-bottom:10px"><div style="display:flex;gap:12px;align-items:flex-start"><div style="font-size:34px">🏕️</div><div style="flex:1"><div style="font-size:10px;color:#4ade80;font-weight:900">${new Date(s.event_date+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}</div><h3 style="margin:4px 0">${esc(s.title)}</h3><div class="msg">${esc(s.club_name)} · ${esc(s.duration)}</div></div><b style="font-size:20px;color:#4ade80">${Number(s.price||0).toFixed(0)} €</b></div><div class="chips" style="margin-top:10px"><span class="chip">📍 ${esc(s.place)} · ${esc(s.city)} ${esc(s.postal_code||'')}</span>${(s.categories||[]).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div>${s.description?`<p>${esc(s.description)}</p>`:''}<div class="profile-actions">${s.contact_phone?`<a class="primary" href="tel:${esc(s.contact_phone)}">📞 Appeler</a>`:''}${s.contact_email?`<a class="secondary" href="mailto:${esc(s.contact_email)}">✉️ Email</a>`:''}</div></article>`).join('')||'<div class="panel"><div class="msg">Aucun stage disponible pour le moment.</div></div>';}
window.openFootShowStages=openStages;
document.addEventListener('DOMContentLoaded',()=>setTimeout(ensureUi,2200));
})();