(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const CATS=['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19','U20','U21','Sénior'];
let profile=null; const uid=()=>window.user?.id||(typeof user!=='undefined'?user?.id:null);
async function getProfile(){if(profile)return profile;const {data}=await sb.from('profiles').select('id,account_type,full_name,club').eq('id',uid()).maybeSingle();return profile=data}
function drawer(){let d=document.getElementById('tournamentsDrawer');if(d)return d;d=document.createElement('section');d.id='tournamentsDrawer';d.className='drawer hidden';d.innerHTML='<div class="drawer-inner"><button class="close" id="closeTournaments">×</button><div id="tournamentsContent"></div></div>';document.body.appendChild(d);d.querySelector('#closeTournaments').onclick=()=>d.classList.add('hidden');return d}
function inject(){if(document.getElementById('openTournaments'))return;const a=document.querySelector('.fs-v2-actions');if(!a)return;const b=document.createElement('button');b.id='openTournaments';b.innerHTML='<span>🏟️</span><b>Tournois</b><small>Tournois des clubs</small>';b.onclick=open;a.appendChild(b)}
async function open(){drawer().classList.remove('hidden');const r=document.getElementById('tournamentsContent'),p=await getProfile();r.innerHTML=`<div class="fs-v2-kicker">ÉVÉNEMENTS CLUBS</div><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><h2>🏟️ Tournois</h2><div class="msg">Découvre les prochains tournois de football.</div></div>${p?.account_type==='recruiter'?'<button class="primary" id="newTournament">+ Publier</button>':''}</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:15px 0"><input id="tourCp" class="input" inputmode="numeric" maxlength="5" placeholder="Code postal"><select id="tourCat" class="input"><option value="">Toutes catégories</option>${CATS.map(x=>`<option>${x}</option>`).join('')}</select></div><div id="tournamentsList"></div>`;document.getElementById('newTournament')?.addEventListener('click',form);document.getElementById('tourCp').oninput=load;document.getElementById('tourCat').onchange=load;load()}
async function load(){const r=document.getElementById('tournamentsList');if(!r)return;r.innerHTML='<div class="msg">Chargement…</div>';let q=sb.from('tournaments').select('*').gte('event_date',new Date().toISOString().slice(0,10)).eq('status','open').order('event_date').limit(100);const cp=document.getElementById('tourCp')?.value.replace(/\D/g,'').slice(0,5)||'';document.getElementById('tourCp').value=cp;if(cp.length===5)q=q.eq('postal_code',cp);const {data,error}=await q;if(error){r.innerHTML='<div class="panel"><b>Active la table Tournois dans Supabase.</b></div>';return}const cat=document.getElementById('tourCat')?.value||'';const rows=(data||[]).filter(x=>!cat||(x.categories||[]).includes(cat));const p=await getProfile();r.innerHTML=rows.length?rows.map(x=>`<article class="panel" style="margin-bottom:10px"><div class="fs-v2-kicker">${esc(x.club_name)}</div><h3>🏆 ${esc(x.title)}</h3><div class="msg">📅 ${new Date(x.event_date+'T12:00:00').toLocaleDateString('fr-FR')}</div><div class="msg">📍 ${esc([x.address,x.postal_code,x.city].filter(Boolean).join(' · '))}</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin:10px 0">${(x.categories||[]).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div>${x.description?`<p>${esc(x.description)}</p>`:''}${x.contact_email||x.contact_phone?`<div class="msg">Contact : ${esc([x.contact_email,x.contact_phone].filter(Boolean).join(' · '))}</div>`:''}${p?.account_type==='recruiter'&&x.club_id===uid()?`<button class="secondary" data-del-tour="${x.id}">Supprimer</button>`:''}</article>`).join(''):'<div class="panel">Aucun tournoi trouvé.</div>';r.querySelectorAll('[data-del-tour]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer ce tournoi ?')){await sb.from('tournaments').delete().eq('id',b.dataset.delTour).eq('club_id',uid());load()}})}
async function form(){const r=document.getElementById('tournamentsContent'),p=await getProfile();r.innerHTML=`<button class="secondary" id="backTour">← Retour</button><h2>🏟️ Publier un tournoi</h2><label>Club</label><input id="tClub" class="input" value="${esc(p?.club||p?.full_name||'')}"><label>Nom du tournoi</label><input id="tTitle" class="input" placeholder="Ex. Tournoi de rentrée U13"><label>Date</label><input id="tDate" type="date" class="input"><label>Lieu / stade</label><input id="tAddress" class="input" placeholder="Nom du stade, adresse"><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="tCp" class="input" maxlength="5" placeholder="Code postal"><input id="tCity" class="input" placeholder="Ville"></div><label>Catégories</label><div style="display:flex;gap:6px;flex-wrap:wrap">${CATS.map(c=>`<label class="chip"><input type="checkbox" name="tCat" value="${c}"> ${c}</label>`).join('')}</div><label>Description</label><textarea id="tDesc" class="input" rows="3"></textarea><label>Email de contact</label><input id="tEmail" class="input" type="email"><label>Téléphone</label><input id="tPhone" class="input" type="tel"><button id="saveTour" class="primary full">Publier le tournoi</button><div id="tMsg" class="msg"></div>`;document.getElementById('backTour').onclick=open;document.getElementById('saveTour').onclick=save}
async function save(){const msg=document.getElementById('tMsg');const payload={club_id:uid(),club_name:tClub.value.trim(),title:tTitle.value.trim(),event_date:tDate.value,address:tAddress.value.trim()||null,postal_code:tCp.value.replace(/\D/g,'').slice(0,5)||null,city:tCity.value.trim(),categories:[...document.querySelectorAll('input[name="tCat"]:checked')].map(x=>x.value),description:tDesc.value.trim()||null,contact_email:tEmail.value.trim()||null,contact_phone:tPhone.value.trim()||null,status:'open'};if(!payload.club_name||!payload.title||!payload.event_date||!payload.city){msg.textContent='Complète le club, le tournoi, la date et la ville.';return}const {error}=await sb.from('tournaments').insert(payload);if(error){msg.textContent=error.message;return}open()}
window.openFootShowTournaments=open;document.addEventListener('DOMContentLoaded',()=>{let n=0;const t=setInterval(()=>{inject();if(document.getElementById('openTournaments')||++n>25)clearInterval(t)},500)});
})();