(()=>{
const plans=[
{icon:'⚡',title:'Vitesse & accélération',level:'30–40 min',goal:'Gagner sur les 5 à 30 premiers mètres',warm:'8 min : footing léger, mobilité hanches/chevilles, montées de genoux, 3 accélérations progressives.',sets:['6 × 10 m départs variés — récupération 60 s','5 × 20 m à intensité élevée — récupération 90 s','4 × 30 m — récupération 2 min','4 × changement de direction 5-10-5 m — récupération 90 s'],finish:'5 min retour au calme. Qualité avant quantité : arrête la série si la vitesse chute nettement.'},
{icon:'💥',title:'Puissance & explosivité',level:'35–45 min',goal:'Améliorer détente, démarrage et puissance des appuis',warm:'10 min : activation + squats au poids du corps + fentes + petits bonds.',sets:['3 × 6 squat jumps — récupération 90 s','3 × 5 bonds horizontaux — récupération 90 s','4 × 5 sauts latéraux par côté','5 × 10 m sprint après 3 sauts explosifs','3 × 8 fentes arrière par jambe'],finish:'Mouvements propres et explosifs. Évite cette séance la veille d’un match.'},
{icon:'🫁',title:'Endurance football',level:'40–50 min',goal:'Tenir une intensité élevée pendant tout le match',warm:'10 min footing facile + mobilité dynamique.',sets:['2 blocs de 8 × 30 s rapide / 30 s lent','3 min de récupération entre les blocs','6 × 100 m à allure soutenue — récupération 45 s','5 min avec ballon : conduite continue à rythme modéré'],finish:'5–8 min de footing très lent et hydratation.'},
{icon:'🔁',title:'Répétition des sprints',level:'30–40 min',goal:'Rester rapide même après plusieurs efforts',warm:'10 min progressif + 3 sprints à 70–85 %.',sets:['2 séries de 6 × 20 m — départ toutes les 25 s','3 min entre les séries','6 × 15 m avec demi-tour à 7,5 m','4 × 30 m avec 30 s de récupération'],finish:'Séance intense : prévois au moins 48 h avant une autre grosse séance de sprint.'},
{icon:'🎯',title:'Agilité & changements de direction',level:'30–40 min',goal:'Être plus vif dans les duels et changements d’appuis',warm:'8 min : mobilité + pas chassés + appuis courts.',sets:['4 × parcours en T','4 × slalom 6 plots espacés de 2 m','5 × réaction gauche/droite sur signal','4 × 10 m avec changement de direction à 5 m','5 min conduite de balle entre plots'],finish:'Cherche des appuis courts, un centre de gravité bas et une relance explosive.'},
{icon:'⚽',title:'Technique sous fatigue',level:'40 min',goal:'Garder de la précision en fin de match',warm:'8 min ballon : conduite, jongles, passes courtes.',sets:['5 × : sprint 15 m + conduite + frappe','4 × 2 min conduite/slalom rapide — 1 min repos','30 passes pied droit + 30 pied gauche contre un mur','4 × : 20 s appuis rapides + contrôle orienté + frappe','Finir par 10 frappes placées de chaque côté'],finish:'La précision reste prioritaire. Réduis l’intensité si la technique se dégrade trop.'},
{icon:'🛡️',title:'Renforcement prévention',level:'30–35 min',goal:'Renforcer jambes et tronc pour mieux résister aux efforts',warm:'7 min mobilité et activation progressive.',sets:['3 × 10 squats contrôlés','3 × 8 fentes par jambe','3 × 12 ponts de hanches','3 × 20–40 s gainage face','3 × 20–30 s gainage latéral par côté','3 × 10 mollets par jambe'],finish:'Progression graduelle. Pas de douleur articulaire : adapte ou arrête l’exercice.'},
{icon:'🌿',title:'Récupération active',level:'20–30 min',goal:'Récupérer entre deux matchs ou séances difficiles',warm:'5 min marche puis footing très facile.',sets:['10–15 min à allure conversationnelle','Mobilité douce : chevilles, hanches, dos','Respiration calme 3–5 min','Hydratation et repas de récupération adaptés'],finish:'Cette séance doit te laisser plus frais qu’au départ.'}
];
function ensure(){let d=document.getElementById('trainingDrawer');if(d)return d;d=document.createElement('section');d.id='trainingDrawer';d.className='drawer hidden';d.innerHTML='<div class="drawer-inner" style="max-width:760px"><button id="closeTraining" class="close">×</button><div id="trainingContent"></div></div>';document.body.appendChild(d);d.querySelector('#closeTraining').onclick=()=>d.classList.add('hidden');return d}
function inject(){if(document.getElementById('openTraining'))return;const grid=document.querySelector('.fs-v2-actions');if(!grid)return;const b=document.createElement('button');b.id='openTraining';b.innerHTML='<span>🏃</span><b>Entraînement</b><small>Programmes football</small>';b.onclick=open;grid.appendChild(b)}
function open(){const d=ensure(),r=document.getElementById('trainingContent');d.classList.remove('hidden');r.innerHTML=`<style>.tr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:15px}.tr-card{background:linear-gradient(145deg,#10251a,#08120d);border:1px solid #294634;border-radius:17px;padding:16px;color:#fff;text-align:left}.tr-card .ico{font-size:30px}.tr-card h3{margin:8px 0 4px}.tr-card small{color:#9eb0a5}.tr-sheet{background:#0c1912;border:1px solid #294634;border-radius:18px;padding:16px;margin-top:12px}.tr-sheet li{margin:10px 0;line-height:1.4}.tr-note{background:#183323;border-left:3px solid #4ade80;padding:12px;border-radius:10px;margin-top:12px}@media(max-width:560px){.tr-grid{grid-template-columns:1fr}}</style><div class="fs-v2-kicker">FOOTSHOW PERFORMANCE</div><h2>🏃 Entraînement</h2><div class="msg">Des séances simples pour développer les qualités utiles au football. Adapte le volume à ton âge, ton niveau et ton calendrier.</div><div class="tr-grid">${plans.map((p,i)=>`<button class="tr-card" data-tr="${i}"><div class="ico">${p.icon}</div><h3>${p.title}</h3><small>${p.level} · ${p.goal}</small></button>`).join('')}</div><div class="tr-note"><b>⚠️ Avant de commencer</b><div class="msg">Échauffe-toi, progresse graduellement et garde au moins un jour léger après une séance très intense. Pour les jeunes joueurs, privilégier la qualité des mouvements et un encadrement adapté.</div></div>`;r.querySelectorAll('[data-tr]').forEach(b=>b.onclick=()=>sheet(+b.dataset.tr))}
function sheet(i){const p=plans[i],r=document.getElementById('trainingContent');r.innerHTML=`<button id="trBack" class="secondary">← Toutes les séances</button><div class="tr-sheet"><div style="font-size:44px">${p.icon}</div><div class="fs-v2-kicker">FICHE ENTRAÎNEMENT</div><h2>${p.title}</h2><p><b>🎯 Objectif :</b> ${p.goal}</p><p><b>⏱️ Durée :</b> ${p.level}</p><h3>🔥 Échauffement</h3><p>${p.warm}</p><h3>🏋️ Séance</h3><ol>${p.sets.map(x=>`<li>${x}</li>`).join('')}</ol><h3>🧘 Fin de séance</h3><p>${p.finish}</p></div>`;document.getElementById('trBack').onclick=open}
window.openFootShowTraining=open;document.addEventListener('DOMContentLoaded',()=>{let n=0;const t=setInterval(()=>{inject();if(document.getElementById('openTraining')||++n>30)clearInterval(t)},500)});
})();